"""
Breast and Axillae Assessment

Evaluate patient breast and axillary system through structured examination including
inspection, palpation, lymph node assessment, and symptom evaluation
using BaseModel definitions and the MedKit AI client with schema-aware prompting.
"""

import sys
import json
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

# Fix import paths
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.pydantic_prompt_generator import PromptStyle
from core.medkit_client import MedKitClient


class BreastQuestion(BaseModel):
    """A single breast/axillae assessment question with guidance."""
    question_number: int = Field(description="Question number")
    question_text: str = Field(description="The breast examination question to ask the patient")
    assessment_domain: str = Field(description="Domain being assessed (e.g., pain, lumps, discharge)")
    clinical_significance: str = Field(description="Why this question matters clinically")
    follow_up_guidance: str = Field(description="How to follow up on responses")


class BreastTestQuestions(BaseModel):
    """Dynamic breast assessment questions generated by LLM."""
    questions: List[BreastQuestion] = Field(description="List of breast assessment questions")
    assessment_context: str = Field(description="Clinical context for breast assessment")


class PatientSymptoms(BaseModel):
    """Patient-reported breast and axillary symptoms."""
    breast_pain: str = Field(description="Any breast pain or tenderness")
    lumps_masses: str = Field(description="Any lumps or masses noticed in the breasts")
    nipple_discharge: str = Field(description="Any nipple discharge (color, consistency, unilateral/bilateral)")
    skin_changes: str = Field(description="Any skin changes on breasts (dimpling, redness, rash)")
    family_history: str = Field(description="Any family history of breast or ovarian cancer")
    axillary_symptoms: str = Field(description="Any lumps, swelling, or tenderness in armpits")
    recent_trauma: str = Field(description="Any recent trauma or injury to breasts or axillae")
    hormonal_changes: str = Field(description="Any hormonal symptoms (cyclical pain, swelling)")


class PhysicalExamination(BaseModel):
    """Physical examination findings."""
    breast_inspection: str = Field(description="Breast inspection findings (asymmetry, skin changes, nipple changes)")
    breast_palpation: str = Field(description="Breast tissue palpation findings (masses, nodules, tenderness)")
    breast_quadrant_assessment: str = Field(description="Assessment of all four quadrants of breast tissue")
    nipple_assessment: str = Field(description="Nipple assessment (retraction, discharge, symmetry)")
    skin_assessment: str = Field(description="Skin assessment (color, texture, rashes, dimpling)")
    axillary_palpation: str = Field(description="Axillary palpation findings (masses, tenderness)")
    axillary_lymph_nodes: str = Field(description="Axillary lymph node assessment (size, consistency, mobility)")
    supraclavicular_lymph_nodes: str = Field(description="Supraclavicular lymph node assessment")
    chest_wall_assessment: str = Field(description="Chest wall assessment (masses, tenderness)")


class RiskFactors(BaseModel):
    """Assessment of breast cancer risk factors."""
    age: str = Field(description="Age (risk increases with age)")
    menarche_age: str = Field(description="Age at menarche (early menarche increases risk)")
    menopause_status: str = Field(description="Menopausal status and age at menopause")
    pregnancy_history: str = Field(description="Number of pregnancies and age at first pregnancy")
    breastfeeding_history: str = Field(description="Duration of breastfeeding (protective factor)")
    hormone_therapy: str = Field(description="Current or past hormone replacement therapy use")
    alcohol_use: str = Field(description="Alcohol consumption frequency")
    obesity_status: str = Field(description="BMI/obesity status")


class BreastAssessmentSummary(BaseModel):
    """Overall breast assessment findings and clinical recommendations."""
    breast_status: str = Field(description="Overall breast status - normal/benign/suspicious/abnormal")
    symptom_summary: str = Field(description="Summary of reported symptoms")
    findings_significance: str = Field(description="Clinical significance of findings - none/benign/concerning/urgent")
    masses_identified: str = Field(description="Any masses identified - none/benign/suspicious/malignant features")
    lymph_node_status: str = Field(description="Lymph node assessment - normal/enlarged/concerning")
    risk_level: str = Field(description="Breast cancer risk level - low/moderate/high/very high")
    imaging_recommendations: str = Field(description="Recommended imaging (mammography, ultrasound, MRI, etc.)")
    specialist_referral: str = Field(description="Whether oncology or breast surgery referral recommended")
    follow_up_plan: str = Field(description="Recommended follow-up plan and timeline")
    patient_education: str = Field(description="Patient education provided regarding breast health and self-exam")


class BreastAxillaeAssessment(BaseModel):
    """
    Comprehensive breast and axillary system assessment.

    Organized as a collection of BaseModel sections, each representing
    distinct aspects of breast and axillary evaluation. Includes patient symptoms,
    physical examination findings, risk factor assessment, and clinical summary.
    """
    # Patient-reported symptoms
    patient_symptoms: PatientSymptoms

    # Physical examination findings
    physical_examination: PhysicalExamination

    # Breast cancer risk factors
    risk_factors: RiskFactors

    # Final assessment summary
    assessment_summary: BreastAssessmentSummary


def generate_breast_questions(
    client: MedKitClient,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> BreastTestQuestions:
    """
    Generate breast and axillae assessment questions using LLM.

    Args:
        client: MedKitClient instance for LLM generation
        patient_context: Optional patient context for question generation
        prompt_style: Style of prompt generation (DETAILED, CONCISE, TECHNICAL)

    Returns:
        BreastTestQuestions with LLM-generated breast assessment questions
    """
    context_note = f"\nPatient context: {patient_context}" if patient_context else ""

    subject = f"""Generate comprehensive breast and axillary assessment questions covering these domains:
1. Patient symptoms (pain, lumps, discharge, skin changes, trauma)
2. Family history (breast cancer, ovarian cancer, genetic risk)
3. Hormonal history (menarche, menopause, pregnancy, breastfeeding, HRT)
4. Risk factors (age, alcohol, obesity, lifestyle)
5. Functional impact (activities affected by symptoms)
6. Physical findings assessment (inspection, palpation, lymph nodes)

Questions should be practical, sensitive, and appropriate for clinical breast assessment.
Include clinical significance and follow-up guidance for each question.{context_note}"""

    sys_prompt = """You are an expert oncologist and breast surgeon. Breast and axillary assessment is crucial in clinical evaluation.

Generate structured clinical questions that are:
- Practical, sensitive, and appropriate for clinical breast assessment
- Including clinical significance and follow-up guidance
- Following medical standards and privacy considerations
- Adhering to current medical guidelines

Return structured JSON matching the exact schema provided, with all required fields populated."""

    return client.generate_text(
        prompt=subject,
        schema=BreastTestQuestions,
        sys_prompt=sys_prompt,
    )


def ask_breast_questions(
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> dict:
    """
    Ask patient breast and axillae assessment questions interactively and collect responses.

    If client is provided, uses LLM to generate dynamic questions.
    Otherwise, uses fallback hardcoded questions.

    Args:
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization
        prompt_style: Style of prompt generation

    Returns:
        Dictionary of patient responses to breast assessment questions
    """
    print("\n" + "="*60)
    print("BREAST AND AXILLAE ASSESSMENT")
    print("="*60)
    print()
    print("MEASURES: This assessment evaluates breast health, identifies potential abnormalities,")
    print("  and screens for breast disease risk factors.")
    print("  • Breast masses, lumps, or thickening")
    print("  • Nipple discharge or changes in appearance")
    print("  • Breast pain, tenderness, or discomfort")
    print("  • Axillary lymph node enlargement")
    print("  • Risk factors for breast cancer and disease")
    print()
    print("TOP 10 KEY ASSESSMENT QUESTIONS:")
    print("  1. Have you noticed any lumps or masses in your breast?")
    print("  2. Have you experienced any breast pain or tenderness?")
    print("  3. Have you noticed any nipple discharge?")
    print("  4. Have you observed any changes in breast size or shape?")
    print("  5. Have you noticed any skin changes on your breast?")
    print("  6. Do you perform regular breast self-examinations?")
    print("  7. When was your last mammogram or breast imaging?")
    print("  8. Do you have a family history of breast cancer?")
    print("  9. Have you noticed any lumps or swelling in your armpits?")
    print(" 10. Are you currently breastfeeding or have you recently?")
    print()
    print("="*60)
    print("DETAILED BREAST AND AXILLAE QUESTIONNAIRE")
    print("="*60)

    responses = {}

    # Generate questions via LLM if client provided
    if client:
        print("\nGenerating breast assessment questions...")
        try:
            breast_qs = generate_breast_questions(client, patient_context, prompt_style)
            print("\n" + "="*60)
            print("BREAST ASSESSMENT QUESTIONS")
            print("="*60)

            for q in breast_qs.questions:
                print(f"\nDomain: {q.assessment_domain}")
                print(f"Clinical Significance: {q.clinical_significance}")
                response = input(f"{q.question_number}. {q.question_text}\n> ").strip()
                responses[f'q{q.question_number}_breast'] = response
                print(f"   [Follow-up: {q.follow_up_guidance}]\n")
        except Exception as e:
            print(f"Warning: Could not generate questions via LLM: {e}")
            print("Using fallback questions...\n")

    # If no LLM generated questions, use fallback
    if not any(k.startswith('q') for k in responses.keys()):
        print("\n" + "="*60)
        print("BREAST ASSESSMENT QUESTIONS (Fallback)")
        print("="*60)

        responses['breast_pain'] = input("Any breast pain or tenderness?: ").strip()
        responses['lumps_masses'] = input("Any lumps or masses noticed in the breasts?: ").strip()
        responses['nipple_discharge'] = input("Any nipple discharge? If yes, color and consistency?: ").strip()
        responses['skin_changes'] = input("Any skin changes (dimpling, redness, rash)?: ").strip()
        responses['family_history'] = input("Any family history of breast or ovarian cancer?: ").strip()
        responses['axillary_symptoms'] = input("Any lumps, swelling, or tenderness in armpits?: ").strip()
        responses['recent_trauma'] = input("Any recent trauma or injury to breasts or axillae?: ").strip()
        responses['hormonal_changes'] = input("Any hormonal symptoms (cyclical pain, swelling)?: ").strip()

    # PHYSICAL EXAMINATION
    print("\n" + "="*60)
    print("PHYSICAL EXAMINATION")
    print("="*60)

    responses['breast_inspection'] = input("Breast inspection findings (asymmetry, skin changes, nipple): ").strip()
    responses['breast_palpation'] = input("Breast tissue palpation findings (masses, nodules, tenderness): ").strip()
    responses['breast_quadrants'] = input("Assessment of all four quadrants of breast tissue: ").strip()
    responses['nipple_assessment'] = input("Nipple assessment (retraction, discharge, symmetry): ").strip()
    responses['skin_assessment'] = input("Skin assessment (color, texture, rashes, dimpling): ").strip()
    responses['axillary_palpation'] = input("Axillary palpation findings (masses, tenderness): ").strip()
    responses['axillary_lymph_nodes'] = input("Axillary lymph node assessment (size, consistency, mobility): ").strip()
    responses['supraclavicular_lymph_nodes'] = input("Supraclavicular lymph node assessment: ").strip()
    responses['chest_wall'] = input("Chest wall assessment (masses, tenderness): ").strip()

    # RISK FACTORS
    print("\n" + "="*60)
    print("RISK FACTORS")
    print("="*60)

    responses['age'] = input("Age (years): ").strip()
    responses['menarche_age'] = input("Age at menarche: ").strip()
    responses['menopause_status'] = input("Menopausal status and age: ").strip()
    responses['pregnancy_history'] = input("Number of pregnancies and age at first pregnancy: ").strip()
    responses['breastfeeding'] = input("Duration of breastfeeding: ").strip()
    responses['hormone_therapy'] = input("Current or past hormone replacement therapy: ").strip()
    responses['alcohol_use'] = input("Alcohol consumption frequency: ").strip()
    responses['obesity_status'] = input("BMI/obesity status: ").strip()

    return responses


def create_breast_assessment_from_responses(
    patient_name: str,
    responses: dict,
    output_path: Optional[Path] = None
) -> BreastAxillaeAssessment:
    """
    Create a structured breast assessment object from collected patient responses.

    Args:
        patient_name: Name of the patient
        responses: Dictionary of patient responses from questions
        output_path: Optional path to save JSON output

    Returns:
        BreastAxillaeAssessment: Validated assessment object
    """
    assessment_data = {
        "patient_symptoms": {
            "breast_pain": responses.get('breast_pain', ''),
            "lumps_masses": responses.get('lumps_masses', ''),
            "nipple_discharge": responses.get('nipple_discharge', ''),
            "skin_changes": responses.get('skin_changes', ''),
            "family_history": responses.get('family_history', ''),
            "axillary_symptoms": responses.get('axillary_symptoms', ''),
            "recent_trauma": responses.get('recent_trauma', ''),
            "hormonal_changes": responses.get('hormonal_changes', '')
        },
        "physical_examination": {
            "breast_inspection": responses.get('breast_inspection', ''),
            "breast_palpation": responses.get('breast_palpation', ''),
            "breast_quadrant_assessment": responses.get('breast_quadrants', ''),
            "nipple_assessment": responses.get('nipple_assessment', ''),
            "skin_assessment": responses.get('skin_assessment', ''),
            "axillary_palpation": responses.get('axillary_palpation', ''),
            "axillary_lymph_nodes": responses.get('axillary_lymph_nodes', ''),
            "supraclavicular_lymph_nodes": responses.get('supraclavicular_lymph_nodes', ''),
            "chest_wall_assessment": responses.get('chest_wall', '')
        },
        "risk_factors": {
            "age": responses.get('age', ''),
            "menarche_age": responses.get('menarche_age', ''),
            "menopause_status": responses.get('menopause_status', ''),
            "pregnancy_history": responses.get('pregnancy_history', ''),
            "breastfeeding_history": responses.get('breastfeeding', ''),
            "hormone_therapy": responses.get('hormone_therapy', ''),
            "alcohol_use": responses.get('alcohol_use', ''),
            "obesity_status": responses.get('obesity_status', '')
        },
        "assessment_summary": {
            "breast_status": "To be determined by clinician",
            "symptom_summary": "To be assessed",
            "findings_significance": "To be determined",
            "masses_identified": "None identified",
            "lymph_node_status": "To be assessed by clinician",
            "risk_level": "To be determined",
            "imaging_recommendations": "To be determined based on findings",
            "specialist_referral": "Not indicated at this time",
            "follow_up_plan": "Routine breast assessment follow-up",
            "patient_education": "Standard breast health and self-examination education provided"
        }
    }

    # Create assessment object
    assessment = BreastAxillaeAssessment(**assessment_data)

    # Save to file if path provided
    if output_path is None:
        output_path = Path("outputs") / f"{patient_name.lower().replace(' ', '_')}_breast_axillae.json"

    # Create outputs directory if it doesn't exist
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save assessment as JSON
    with open(output_path, 'w') as f:
        json.dump(assessment.model_dump(), f, indent=2)

    print(f"\n✓ Assessment saved to: {output_path}")

    return assessment


def evaluate_breast_axillae(
    patient_name: str,
    output_path: Optional[Path] = None,
    use_schema_prompt: bool = True,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
) -> BreastAxillaeAssessment:
    """
    Evaluate patient breast and axillary system through structured assessment.

    Args:
        patient_name: Name or identifier of the patient
        output_path: Optional path to save JSON output
        use_schema_prompt: Whether to use schema-aware prompting
        prompt_style: Style of prompt generation
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization

    Returns:
        BreastAxillaeAssessment: Validated breast assessment object
    """
    if not patient_name or not patient_name.strip():
        raise ValueError("Patient name cannot be empty")

    print(f"\nStarting breast and axillae assessment for: {patient_name}")
    responses = ask_breast_questions(client, patient_context, prompt_style)

    assessment = create_breast_assessment_from_responses(patient_name, responses, output_path)

    return assessment


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description="Evaluate patient breast and axillary system through structured assessment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default - saves to outputs/unknown_breast_axillae.json
  python exam_breast_axillae.py

  # With patient name
  python exam_breast_axillae.py "Jane Doe"

  # Custom output path
  python exam_breast_axillae.py "Jane Doe" -o custom_assessment.json

  # With concise prompting
  python exam_breast_axillae.py "Jane Doe" --concise

Breast and Axillae Assessment Protocol:
  1. PATIENT SYMPTOMS:
     - Breast pain or tenderness
     - Lumps or masses
     - Nipple discharge (character, unilateral/bilateral)
     - Skin changes (dimpling, redness, rash)
     - Axillary symptoms (swelling, lumps, tenderness)
     - Family history (breast, ovarian cancer)
     - Recent trauma

  2. PHYSICAL EXAMINATION:
     - Breast inspection (asymmetry, skin, nipples)
     - Breast palpation (all quadrants, masses, tenderness)
     - Nipple assessment (retraction, discharge, symmetry)
     - Axillary palpation (masses, nodes, tenderness)
     - Lymph node assessment (axillary, supraclavicular)

  3. RISK FACTOR ASSESSMENT:
     - Age, menarche age, menopause status
     - Pregnancy and breastfeeding history
     - Hormone therapy use
     - Lifestyle factors (alcohol, obesity)
        """
    )
    parser.add_argument("patient", nargs='*', default=['unknown'], help="Name or identifier of the patient (default: 'unknown')")
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Path to save JSON output. Defaults to outputs/{patient_name}_breast_axillae.json"
    )
    parser.add_argument(
        "--concise",
        action="store_true",
        help="Use concise prompt style (faster generation)"
    )

    args = parser.parse_args()

    try:
        patient_name = " ".join(args.patient)
        prompt_style = PromptStyle.CONCISE if args.concise else PromptStyle.DETAILED

        result = evaluate_breast_axillae(
            patient_name=patient_name,
            output_path=args.output,
            prompt_style=prompt_style,
        )
        print("✓ Success!")

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
