"""
Depression Screening Assessment

Evaluate patient depression status through structured screening questions
and validated assessment tools using BaseModel definitions and the MedKit
AI client with schema-aware prompting.
"""

import sys
import json
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional, List

# Fix import paths
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.pydantic_prompt_generator import PromptStyle
from core.medkit_client import MedKitClient


class DepressionQuestion(BaseModel):
    """A single depression screening question with clinical guidance."""
    question_number: int = Field(description="Question number")
    question_text: str = Field(description="The depression screening question")
    assessment_domain: str = Field(description="Domain being assessed (e.g., core symptoms, fatigue, concentration)")
    clinical_significance: str = Field(description="Why this question matters clinically")
    follow_up_guidance: str = Field(description="How to follow up on responses")


class DepressionTestQuestions(BaseModel):
    """Dynamic depression screening questions generated by LLM."""
    questions: List[DepressionQuestion] = Field(description="List of depression screening questions")
    assessment_context: str = Field(description="Clinical context for depression assessment")


class CoreDepressionSymptoms(BaseModel):
    """Assessment of core depression symptoms over the past 2 weeks."""
    depressed_mood: str = Field(description="Over the past 2 weeks, have you felt down, depressed, or hopeless? Response: yes/no. If yes, how often - daily/most days/several days/1-2 days")
    anhedonia_loss_of_interest: str = Field(description="Over the past 2 weeks, have you felt little interest or pleasure in doing things? Response: yes/no. If yes, does this affect most activities or specific areas")
    symptom_duration: str = Field(description="Duration of symptoms - present for 2 weeks continuously/intermittent over 2 weeks/occurred for less than 2 weeks")
    symptom_severity: str = Field(description="Severity of core symptoms - mild/moderate/moderate to severe/severe")
    core_symptom_count: str = Field(description="Number of core depression symptoms present - 0/1/2 (2+ required for depression diagnosis)")
    screening_risk_level: str = Field(description="Depression risk based on core symptoms - low risk/at-risk/high risk/very high risk")


class MoodSymptoms(BaseModel):
    """Assessment of mood-related symptoms and emotional functioning."""
    persistent_sad_mood: str = Field(description="Persistent sad, empty, or irritable mood throughout the day - yes/no. Frequency: daily/most days/several days/rarely")
    mood_variability: str = Field(description="Mood variability throughout the day - stable/slightly variable/significantly variable/severe mood swings. Better or worse at certain times?")
    irritability: str = Field(description="Increased irritability or anger - not present/mild/moderate/severe. Easily triggered by minor frustrations?")
    emotional_numbness: str = Field(description="Emotional numbness or blunting - not present/mild/moderate/severe")
    crying_episodes: str = Field(description="Crying spells or tearfulness - not present/occasional/frequent/uncontrollable. Triggered or unprovoked?")
    anxiety_with_depression: str = Field(description="Anxiety accompanying depression - not present/mild/moderate/severe")
    emotional_pain: str = Field(description="Patient describes emotional pain or suffering - yes/no. Intensity: mild/moderate/severe/unbearable")


class FatigueAssessment(BaseModel):
    """Detailed assessment of fatigue and loss of energy."""
    fatigue_presence: str = Field(description="Have you experienced fatigue or loss of energy over the past 2 weeks? yes/no. If yes, is it constant or intermittent?")
    fatigue_severity: str = Field(description="Severity of fatigue - mild (manageable)/moderate (interferes with some activities)/severe (interferes with most activities)/extreme (cannot perform daily tasks)")
    fatigue_pattern: str = Field(description="Pattern of fatigue - worse in morning/worse in afternoon/worse in evening/constant throughout day/unpredictable")
    energy_level_change: str = Field(description="Change in energy compared to baseline - slight decrease/moderate decrease/significant decrease/completely exhausted")
    morning_fatigue: str = Field(description="Fatigue upon waking in morning - refreshed/tired/extremely tired/unable to get out of bed")
    afternoon_fatigue: str = Field(description="Fatigue in afternoon hours - manageable/significant/overwhelming")
    physical_exhaustion: str = Field(description="Physical exhaustion even with minimal activity - yes/no. Can you climb stairs, walk, or do light tasks?")
    fatigue_worsening_factors: str = Field(description="What makes fatigue worse? (physical activity/mental effort/stress/lack of sleep/none identified), comma-separated")
    fatigue_improving_factors: str = Field(description="What helps fatigue? (rest/caffeine/activity/social contact/medication/nothing helps), comma-separated")
    fatigue_impact_daily_life: str = Field(description="How much does fatigue impact your daily life? Minimal/mild/moderate/severe/unable to function. Specific examples?")
    impact_on_work_school: str = Field(description="Impact on work or school performance - none/slightly reduced productivity/moderately reduced/significantly impaired/unable to work")
    impact_on_social: str = Field(description="Impact on social activities - participates normally/reduced participation/mostly avoids/complete withdrawal")
    impact_on_self_care: str = Field(description="Impact on self-care (grooming, hygiene, dressing) - maintained normally/some neglect/significant neglect/unable to maintain")
    fatigue_distinct_from_sadness: str = Field(description="Is fatigue distinct from sadness/depression mood, or part of overall depressed feeling? Distinct/combined/unclear")


class RestlessnessAssessment(BaseModel):
    """Detailed assessment of restlessness and agitation."""
    restlessness_presence: str = Field(description="Have you felt restless or unable to sit still over the past 2 weeks? yes/no. If yes, how often - daily/most days/several days")
    restlessness_type: str = Field(description="Type of restlessness - difficulty sitting still/fidgeting/pacing/unable to relax/inner sense of restlessness/all of above")
    restlessness_severity: str = Field(description="Severity - mild (noticeable to patient)/moderate (visible to others)/severe (interferes with function)/extreme (unbearable)")
    agitation_level: str = Field(description="Level of agitation or irritable energy - not present/mild/moderate/severe. Observable by others?")
    physical_manifestations: str = Field(description="Physical manifestations of restlessness - fidgeting/leg bouncing/pacing/hand wringing/tapping/unable to sit still/constantly moving")
    restlessness_pattern: str = Field(description="Pattern of restlessness - present throughout day/worse at certain times/episodic/worse during certain activities")
    sense_of_urgency: str = Field(description="Sense of internal urgency or pressure - none/mild/moderate/severe. Feeling need to be doing something?")
    racing_thoughts: str = Field(description="Racing or pressured thoughts accompanying restlessness - none/some/frequent/constant")
    sleep_impact: str = Field(description="Impact of restlessness on sleep - none/difficulty falling asleep/frequent waking/non-restorative/severe insomnia")
    daily_function_impact: str = Field(description="Impact on daily functioning - minimal/mild/moderate/severe. Can you sit through meetings, meals, conversations?")
    work_impact: str = Field(description="Impact on work/school - none/some difficulty concentrating/productivity affected/unable to work")
    relationship_impact: str = Field(description="Impact on relationships - relationships fine/others notice irritability/tension with others/conflict/withdrawn")
    restlessness_vs_anxiety: str = Field(description="Is restlessness part of anxiety, or distinct depression symptom? Separate from anxiety/part of anxiety/unclear")
    attempts_to_manage: str = Field(description="What helps reduce restlessness? (exercise/activity/medication/alcohol/nothing), comma-separated")


class ConcentrationAssessment(BaseModel):
    """Detailed assessment of poor concentration and cognitive difficulties."""
    concentration_difficulty: str = Field(description="Over the past 2 weeks, have you had trouble concentrating? yes/no. If yes, is difficulty mild/moderate/severe/extreme")
    concentration_pattern: str = Field(description="Pattern of difficulty - constant/worse with fatigue/worse with stress/intermittent/worse on certain tasks")
    attention_span: str = Field(description="Attention span changes - can focus for hours/30+ minutes/10-30 minutes/less than 10 minutes/cannot focus at all")
    specific_task_difficulty: str = Field(description="Difficulty with specific tasks - reading/writing/calculations/conversations/complex tasks/all tasks/none improved")
    mind_wandering: str = Field(description="Mind wandering or racing thoughts - not present/occasional/frequent/constant/uncontrollable. Content of wandering?")
    forgetfulness: str = Field(description="Forgetfulness or memory problems - not present/occasional (normal)/frequent/severe. Affecting work or daily life?")
    decision_making: str = Field(description="Difficulty making decisions - none/minor hesitation/significant difficulty/unable to decide/avoids decisions. What types of decisions?")
    work_school_impact: str = Field(description="Impact on work or school - none/minor impact/moderate impact/significant impact/unable to work/failing classes")
    reading_comprehension: str = Field(description="Difficulty reading and understanding material - none/must reread often/cannot comprehend/unable to read")
    conversation_engagement: str = Field(description="Difficulty following conversations - none/occasionally misses points/frequently loses track/cannot follow/avoids")
    task_completion: str = Field(description="Ability to complete tasks - completes easily/needs reminders/difficulty following through/cannot complete/abandons tasks")
    mental_effort_required: str = Field(description="Effort required for mental tasks that were previously easy - minimal extra effort/moderate effort needed/significant effort/overwhelming/impossible")
    time_perception: str = Field(description="Does time feel like it passes differently? Normally/slower/faster/unclear")
    concentration_worse_morning_evening: str = Field(description="When is concentration worst? Morning/afternoon/evening/all day same/unpredictable")
    triggers_concentration_loss: str = Field(description="What makes concentration worse? (stress/fatigue/medication/noise/other), comma-separated")
    concentration_improving_factors: str = Field(description="What helps concentration? (coffee/medication/quiet/activity/structure/nothing), comma-separated")
    concentration_vs_mood: str = Field(description="Is poor concentration due to depression, or separate symptom? Part of depression/separate issue/unclear")


class CognitiveSymptoms(BaseModel):
    """Assessment of cognitive symptoms associated with depression."""
    hopelessness: str = Field(description="Feelings of hopelessness or negative outlook about future - not present/mild/moderate/severe")
    worthlessness: str = Field(description="Feelings of worthlessness or excessive guilt - not present/mild/moderate/severe")
    self_criticism: str = Field(description="Negative self-talk or self-blame - absent/occasional/frequent/pervasive")
    rumination: str = Field(description="Rumination or repetitive negative thinking - absent/occasional/frequent/preoccupying")
    death_thoughts: str = Field(description="Thoughts about death or dying (not including fear of death) - not present/occasional/frequent/persistent")
    suicidal_ideation: str = Field(description="Suicidal thoughts or wishes - absent/passive wishes to die/occasional active ideation/frequent/with plan or intent")


class SuicideRiskAssessment(BaseModel):
    """Assessment of suicide risk - CRITICAL SCREENING."""
    suicidal_thoughts_presence: str = Field(description="Have you had any suicidal thoughts in the past 2 weeks? Yes/No. If yes: occasional/frequent/persistent/intrusive")
    suicidal_intent: str = Field(description="Do you intend to act on these thoughts? No/Unsure/Yes. Any current plan?")
    suicide_plan_specificity: str = Field(description="Specificity of plan if present - no plan/vague idea/specific method/detailed plan with timeline/means available")
    protective_factors: str = Field(description="Protective factors present - family responsibilities/religious beliefs/hopes for future/fear of death/lack of means/other reasons to live")
    past_suicide_attempts: str = Field(description="History of suicide attempts - none/one attempt/multiple attempts. When and method?")
    current_access_to_means: str = Field(description="Access to means of suicide - no access/possible access/easy access/means readily available")
    risk_level: str = Field(description="Overall suicide risk level - low/moderate/high/very high/imminent")
    crisis_intervention_needed: str = Field(description="Immediate crisis intervention or safety planning needed? No/Yes - consider emergency services if yes")


class MotivationAndFunctioning(BaseModel):
    """Assessment of motivation, energy, and daily functioning."""
    motivation_loss: str = Field(description="Loss of motivation or initiative - not present/mild/moderate/severe. Difficulty starting activities?")
    psychomotor_retardation: str = Field(description="Slowness of movement or speech (psychomotor retardation) - not present/mild/moderate/severe")
    psychomotor_agitation: str = Field(description="Restlessness or inability to sit still (psychomotor agitation) - not present/mild/moderate/severe")
    work_school_function: str = Field(description="Ability to function at work or school - normal/slightly impaired/moderately impaired/severely impaired/unable")
    social_function: str = Field(description="Ability to engage socially - normal/slightly impaired/moderately impaired/severely impaired/withdrawn")
    self_care: str = Field(description="Self-care and hygiene - maintained/somewhat neglected/significantly neglected/severely neglected")
    withdrawal_isolation: str = Field(description="Social withdrawal or isolation - not present/mild/moderate/severe/complete withdrawal")


class SleepAndAppetite(BaseModel):
    """Assessment of sleep and appetite changes associated with depression."""
    sleep_insomnia: str = Field(description="Insomnia - early morning awakening/middle-of-night insomnia/difficulty falling asleep/multiple types/not present")
    sleep_hypersomnia: str = Field(description="Hypersomnia or sleeping too much - not present/occasional/daily/extreme")
    sleep_quality: str = Field(description="Quality of sleep when able to sleep - good/fair/poor/very poor/unrefreshing")
    sleep_pattern_change: str = Field(description="Significant change in sleep pattern from baseline - yes/no/unclear")
    appetite_loss: str = Field(description="Loss of appetite - not present/mild/moderate/severe/complete anorexia")
    appetite_increase: str = Field(description="Increased appetite - not present/mild/moderate/severe")
    appetite_pattern_change: str = Field(description="Significant change in appetite from baseline - yes/no/unclear")
    weight_change: str = Field(description="Unintentional weight change - no change/weight loss/weight gain. Approximate amount and timeframe")
    nutritional_status: str = Field(description="Current nutritional status concerns - adequate/mild concerns/moderate concerns/severe")


class SocialAndRelationships(BaseModel):
    """Assessment of social and relationship impacts of depression."""
    social_support: str = Field(description="Adequacy of social support - strong support/moderate support/limited support/isolated/no support")
    relationship_quality: str = Field(description="Quality of close relationships - good/fair/strained/conflicted/estranged")
    loneliness: str = Field(description="Feelings of loneliness - not present/occasional/frequent/persistent/overwhelming")
    burden_to_others: str = Field(description="Belief that patient is burden to others - disagree/uncertain/agree/strongly agree")
    interpersonal_effectiveness: str = Field(description="Ability to communicate needs and maintain relationships - good/fair/poor/significantly impaired")


class DurationAndCourse(BaseModel):
    """Assessment of depression timeline and course."""
    episode_onset: str = Field(description="When did this depressive episode begin? Specific date/approximate timeframe/gradual onset/sudden onset")
    episode_duration: str = Field(description="Duration of current episode - less than 2 weeks/2-4 weeks/1-3 months/3-6 months/6-12 months/over 1 year")
    previous_episodes: str = Field(description="History of previous depressive episodes - none/one previous/recurrent (2-3 episodes)/chronic (frequent episodes)")
    seasonal_pattern: str = Field(description="Seasonal pattern to depression - no pattern/worse in winter/worse in summer/worse in spring/worse in fall/cyclical")
    triggers_identified: str = Field(description="Identifiable triggers or stressors for this episode - no clear trigger/specific life event/stress accumulation/unclear")
    remission_pattern: str = Field(description="Pattern of remission from past episodes - full remission/partial remission/ongoing symptoms between episodes/chronic")


class MedicalAndContextualFactors(BaseModel):
    """Assessment of medical conditions and contextual factors."""
    past_psychiatric_history: str = Field(description="Past psychiatric history - none/depression/bipolar disorder/anxiety disorder/other. Treatment received?")
    family_psychiatric_history: str = Field(description="Family history of depression or psychiatric illness - none/parent/sibling/multiple family members/strong family history")
    medical_conditions: str = Field(description="Medical conditions that could contribute to depression (thyroid, chronic pain, cancer, etc.) - none/one or more/significant")
    medications_affect_mood: str = Field(description="Current medications that may affect mood - none/possible impact/known depression side effect")
    substance_use_impact: str = Field(description="Alcohol or substance use as contributing factor - not reported/occasional/frequent/significant/dependence")
    life_stressors: str = Field(description="Current life stressors (job loss, relationship, financial, health, loss, etc.), comma-separated")
    trauma_history: str = Field(description="History of trauma or adverse childhood experiences - none/remote/recent/ongoing/multiple traumas")
    sleep_deprivation: str = Field(description="Sleep deprivation as contributing factor - not applicable/possible/likely/significant factor")


class PriorTreatmentHistory(BaseModel):
    """Assessment of previous depression treatments and response."""
    previous_antidepressants: str = Field(description="Previous antidepressant trials - none/one/multiple. Which medications and response?")
    previous_psychotherapy: str = Field(description="Previous psychotherapy - none/CBT/IPT/psychodynamic/other. Duration and effectiveness?")
    previous_hospitalization: str = Field(description="Previous psychiatric hospitalization - none/voluntary admission/involuntary/multiple/recent")
    treatment_compliance: str = Field(description="Compliance with past treatments - good/fair/poor/inconsistent/resistant")
    current_treatment: str = Field(description="Current treatment for depression - none/medication/therapy/combined/other")


class AssessmentSummary(BaseModel):
    """Overall depression screening findings and clinical recommendations."""
    depression_screening_result: str = Field(description="Depression screening result - negative (no depression)/possible depression/probable depression/likely depression")
    depression_severity: str = Field(description="Depression severity if present - mild/moderate/moderate-severe/severe/severe with psychotic features")
    core_symptoms_present: str = Field(description="Core symptoms present (depressed mood and/or anhedonia) - none/one/both")
    symptom_count: str = Field(description="Total number of depression symptoms present")
    prominent_symptoms: str = Field(description="Most prominent symptoms (e.g., fatigue, poor concentration, restlessness, low mood, anhedonia), comma-separated")
    functional_impairment: str = Field(description="Degree of functional impairment - none/mild/moderate/severe/profound")
    suicide_risk: str = Field(description="Suicide risk assessment - low/moderate/high/very high/imminent danger")
    depression_type: str = Field(description="Type of depression suggested by presentation - major depressive disorder/persistent depressive disorder (dysthymia)/other specified depressive disorder/situational depression/adjustment disorder with depressed mood")
    comorbid_conditions: str = Field(description="Comorbid conditions identified (anxiety, substance use, medical conditions, etc.), comma-separated")
    protective_strengths: str = Field(description="Patient strengths and protective factors (social support, coping skills, insight, motivation, etc.), comma-separated")
    recommendations: str = Field(description="Clinical recommendations (medication, therapy, lifestyle changes, support, etc.), comma-separated")
    specialist_referral: str = Field(description="Referral needed? To psychiatry (medication)/therapist (psychotherapy)/both/emergency services. Urgency level?")


class DepressionScreeningAssessment(BaseModel):
    """
    Comprehensive depression screening assessment.

    Organized as a collection of BaseModel sections, each representing
    distinct aspects of depression evaluation. Includes core symptoms,
    mood assessment, detailed fatigue assessment, detailed restlessness
    assessment, detailed poor concentration assessment, cognitive symptoms,
    suicide risk (critical), motivation and functioning, sleep and appetite,
    relationships, timeline, medical/contextual factors, and treatment history.
    """
    # Core depression symptoms (2-week screening)
    core_depression_symptoms: CoreDepressionSymptoms

    # Mood symptoms and emotional functioning
    mood_symptoms: MoodSymptoms

    # Fatigue and loss of energy - DETAILED
    fatigue_assessment: FatigueAssessment

    # Restlessness and agitation - DETAILED
    restlessness_assessment: RestlessnessAssessment

    # Poor concentration and cognitive difficulties - DETAILED
    concentration_assessment: ConcentrationAssessment

    # Other cognitive symptoms of depression
    cognitive_symptoms: CognitiveSymptoms

    # Suicide risk assessment - CRITICAL
    suicide_risk_assessment: SuicideRiskAssessment

    # Motivation, energy, and daily functioning
    motivation_and_functioning: MotivationAndFunctioning

    # Sleep and appetite changes
    sleep_and_appetite: SleepAndAppetite

    # Social and relationship impacts
    social_and_relationships: SocialAndRelationships

    # Duration and course of depression
    duration_and_course: DurationAndCourse

    # Medical and contextual factors
    medical_and_contextual_factors: MedicalAndContextualFactors

    # Prior treatment history
    prior_treatment_history: PriorTreatmentHistory

    # Final assessment
    assessment_summary: AssessmentSummary


def generate_depression_questions(
    client: MedKitClient,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> DepressionTestQuestions:
    """
    Generate depression screening questions using LLM.

    Args:
        client: MedKitClient instance for LLM access
        patient_context: Optional patient-specific context for personalized questions
        prompt_style: Style of schema prompt (DETAILED, CONCISE, TECHNICAL)

    Returns:
        DepressionTestQuestions: Generated questions with clinical guidance
    """
    context = patient_context or "Standard depression screening protocol"

    prompt = f"""Generate comprehensive depression screening questions for a patient.

Patient Context: {context}

Create questions that assess:
1. Core depression symptoms (depressed mood, anhedonia)
2. Fatigue and energy levels
3. Restlessness and agitation
4. Concentration and cognitive difficulties
5. Sleep and appetite changes
6. Suicidal ideation (critical assessment)
7. Functional impairment
8. Treatment history

For each question, provide:
- Question text
- Assessment domain
- Clinical significance (why it matters)
- Follow-up guidance (how to respond to answers)

Ensure questions are compassionate, non-judgmental, and clinically appropriate."""

    sys_prompt = """You are an expert psychiatrist and mental health clinician specializing in depression assessment.

Generate comprehensive depression screening questions that are:
- Compassionate and non-judgmental
- Clinically appropriate and evidence-based
- Following current DSM-5 and clinical guidelines
- Sensitive to suicidal ideation assessment

Return structured JSON matching the exact schema provided, with all required fields populated."""

    return client.generate_text(
        prompt=prompt,
        schema=DepressionTestQuestions,
        sys_prompt=sys_prompt,
    )


def ask_depression_screening_questions(
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> dict:
    """
    Ask depression screening questions interactively and collect responses.

    Args:
        client: Optional MedKitClient for LLM-generated questions
        patient_context: Optional patient-specific context
        prompt_style: Style of schema prompt (DETAILED, CONCISE, TECHNICAL)

    Returns:
        Dictionary of patient responses.
    """
    # Try to generate questions with LLM if client available
    if client is not None:
        try:
            llm_questions = generate_depression_questions(client, patient_context, prompt_style)
            print("\n" + "="*70)
            print("DEPRESSION SCREENING ASSESSMENT (LLM-GENERATED QUESTIONS)")
            print("="*70)
            print("\nPlease answer the following questions honestly. This assessment")
            print("helps us understand your mental health over the past 2 weeks.\n")

            responses = {}
            for q in llm_questions.questions:
                response = input(f"{q.question_number}. {q.question_text}\n   Clinical Context: {q.clinical_significance}\n   > ").strip()
                responses[f"q{q.question_number}_{q.assessment_domain}"] = response

            return responses
        except Exception as e:
            print(f"\n⚠️  Could not generate LLM questions: {e}")
            print("Falling back to standard questions...\n")

    # Fall back to standard questions
    print("\n" + "="*70)
    print("DEPRESSION SCREENING ASSESSMENT")
    print("="*70)
    print()
    print("MEASURES: This assessment screens for depressive symptoms and evaluates their")
    print("  severity and impact on daily functioning.")
    print("  • Core depression symptoms (depressed mood, anhedonia)")
    print("  • Vegetative symptoms (sleep, appetite, energy changes)")
    print("  • Cognitive symptoms (concentration, worthlessness, guilt)")
    print("  • Psychomotor changes (agitation or retardation)")
    print("  • Suicidal ideation and risk assessment")
    print()
    print("TOP 10 KEY ASSESSMENT QUESTIONS:")
    print("  1. Over the past 2 weeks, have you felt down, depressed, or hopeless?")
    print("  2. Have you felt little interest or pleasure in doing things?")
    print("  3. Have you experienced fatigue or loss of energy?")
    print("  4. Have you had trouble sleeping or been sleeping too much?")
    print("  5. Have you noticed changes in your appetite or weight?")
    print("  6. Have you had trouble concentrating on things?")
    print("  7. Have you felt bad about yourself or that you're a failure?")
    print("  8. Have you been moving or speaking slowly, or been restless?")
    print("  9. Have you thought that you would be better off dead?")
    print(" 10. How much have these problems affected your daily functioning?")
    print()
    print("="*70)
    print("DETAILED DEPRESSION SCREENING QUESTIONNAIRE")
    print("="*70)
    print("\nPlease answer the following questions honestly. This assessment")
    print("helps us understand your mental health over the past 2 weeks.\n")

    responses = {}

    # CORE SCREENING QUESTIONS
    print("--- CORE SCREENING QUESTIONS (Past 2 Weeks) ---")
    responses['depressed_mood'] = input("Over the past 2 weeks, have you felt down, depressed, or hopeless? (yes/no): ").strip().lower()
    if responses['depressed_mood'] == 'yes':
        responses['depressed_mood_frequency'] = input("  How often? (daily/most days/several days/1-2 days): ").strip()
    responses['anhedonia'] = input("Over the past 2 weeks, have you felt little interest or pleasure in doing things? (yes/no): ").strip().lower()
    if responses['anhedonia'] == 'yes':
        responses['anhedonia_scope'] = input("  Does this affect most activities or specific areas? ").strip()

    # FATIGUE ASSESSMENT
    print("\n--- FATIGUE AND ENERGY (Past 2 Weeks) ---")
    responses['fatigue_present'] = input("Have you experienced fatigue or loss of energy? (yes/no): ").strip().lower()
    if responses['fatigue_present'] == 'yes':
        responses['fatigue_severity'] = input("  Severity (mild/moderate/severe/extreme): ").strip()
        responses['fatigue_pattern'] = input("  When is fatigue worst? (morning/afternoon/evening/constant): ").strip()
        responses['fatigue_impact'] = input("  How much does it impact daily life? (minimal/mild/moderate/severe/unable to function): ").strip()
        responses['fatigue_factors'] = input("  What makes it better or worse? ").strip()

    # RESTLESSNESS ASSESSMENT
    print("\n--- RESTLESSNESS AND AGITATION ---")
    responses['restlessness'] = input("Have you felt restless or unable to sit still? (yes/no): ").strip().lower()
    if responses['restlessness'] == 'yes':
        responses['restlessness_type'] = input("  Type (fidgeting/pacing/inability to relax/agitation): ").strip()
        responses['restlessness_severity'] = input("  Severity (mild/moderate/severe): ").strip()
        responses['restlessness_impact'] = input("  Impact on sleep or daily activities? ").strip()

    # CONCENTRATION ASSESSMENT
    print("\n--- CONCENTRATION AND THINKING ---")
    responses['concentration_difficulty'] = input("Have you had trouble concentrating or focusing? (yes/no): ").strip().lower()
    if responses['concentration_difficulty'] == 'yes':
        responses['concentration_severity'] = input("  How severe? (mild/moderate/severe): ").strip()
        responses['concentration_examples'] = input("  Examples (reading/work/conversations): ").strip()
        responses['concentration_impact'] = input("  Impact on work/school/daily tasks? ").strip()

    # MOOD AND EMOTIONS
    print("\n--- MOOD AND EMOTIONS ---")
    responses['mood_description'] = input("Describe your mood over the past 2 weeks: ").strip()
    responses['irritability'] = input("Have you been more irritable than usual? (yes/no): ").strip().lower()
    responses['crying_spells'] = input("Any crying spells or tearfulness? (yes/no): ").strip().lower()
    responses['emotional_numbness'] = input("Do you feel emotionally numb or disconnected? (yes/no): ").strip().lower()

    # SLEEP AND APPETITE
    print("\n--- SLEEP AND APPETITE ---")
    responses['sleep_changes'] = input("Have your sleep patterns changed? Describe: ").strip()
    responses['appetite_changes'] = input("Have your appetite or weight changed? Describe: ").strip()

    # MOTIVATION AND FUNCTIONING
    print("\n--- MOTIVATION AND FUNCTIONING ---")
    responses['motivation_loss'] = input("Have you lost motivation or interest in activities you normally enjoy? (yes/no): ").strip().lower()
    responses['work_function'] = input("How is your ability to function at work/school? (normal/slightly impaired/moderately impaired/severely impaired): ").strip()
    responses['social_function'] = input("How is your social functioning? (normal/withdrawn/isolated): ").strip()
    responses['self_care'] = input("How is your self-care (hygiene, grooming)? (maintained/somewhat neglected/significantly neglected): ").strip()

    # CRITICAL - SUICIDE RISK ASSESSMENT
    print("\n" + "!"*70)
    print("CRITICAL SAFETY QUESTIONS")
    print("!"*70)
    responses['suicidal_thoughts'] = input("Have you had any thoughts of harming yourself or ending your life? (yes/no): ").strip().lower()
    if responses['suicidal_thoughts'] == 'yes':
        responses['suicide_plan'] = input("  Do you have a plan? (yes/no): ").strip().lower()
        responses['suicide_intent'] = input("  Do you intend to act on these thoughts? (yes/no/unsure): ").strip().lower()
        responses['suicide_means'] = input("  Do you have access to means? (yes/no): ").strip().lower()
        print("\n⚠️  IMMEDIATE SAFETY ASSESSMENT NEEDED - Consider emergency services")

    # TIMELINE AND HISTORY
    print("\n--- TIMELINE AND HISTORY ---")
    responses['symptom_onset'] = input("When did these symptoms start? ").strip()
    responses['previous_episodes'] = input("Have you had previous depressive episodes? (yes/no): ").strip().lower()
    if responses['previous_episodes'] == 'yes':
        responses['previous_episodes_detail'] = input("  How many and when? ").strip()
    responses['family_history'] = input("Does depression run in your family? (yes/no): ").strip().lower()

    # TREATMENTS
    print("\n--- TREATMENTS ---")
    responses['previous_treatment'] = input("Have you received mental health treatment before? (yes/no): ").strip().lower()
    if responses['previous_treatment'] == 'yes':
        responses['previous_treatment_type'] = input("  Type (medication/therapy/both/hospitalization): ").strip()
    responses['current_treatment'] = input("Are you currently receiving treatment? (yes/no): ").strip().lower()
    responses['current_medications'] = input("Are you on any medications? If yes, list them: ").strip()

    # STRESSORS AND SUPPORT
    print("\n--- STRESSORS AND SUPPORT ---")
    responses['recent_stressors'] = input("What recent stressors or life changes have you experienced? ").strip()
    responses['social_support'] = input("Do you have adequate social support? (yes/no/limited): ").strip()

    return responses


def create_depression_assessment_from_responses(patient_name: str, responses: dict, output_path: Optional[Path] = None) -> DepressionScreeningAssessment:
    """
    Create a structured depression screening assessment from patient responses.
    """
    import json

    # Build assessment data from responses
    assessment_data = {
        "core_depression_symptoms": {
            "depressed_mood": f"yes - {responses.get('depressed_mood_frequency', 'unspecified')}" if responses.get('depressed_mood') == 'yes' else "no",
            "anhedonia_loss_of_interest": f"yes - {responses.get('anhedonia_scope', 'unspecified')}" if responses.get('anhedonia') == 'yes' else "no",
            "symptom_duration": responses.get('symptom_onset', 'unknown'),
            "symptom_severity": "To be determined by clinician",
            "core_symptom_count": "2" if responses.get('depressed_mood') == 'yes' and responses.get('anhedonia') == 'yes' else "1" if responses.get('depressed_mood') == 'yes' or responses.get('anhedonia') == 'yes' else "0",
            "screening_risk_level": "high risk" if responses.get('depressed_mood') == 'yes' and responses.get('anhedonia') == 'yes' else "at-risk" if responses.get('depressed_mood') == 'yes' or responses.get('anhedonia') == 'yes' else "low risk"
        },
        "mood_symptoms": {
            "persistent_sad_mood": responses.get('mood_description', ''),
            "mood_variability": "variable throughout day based on patient report",
            "irritability": responses.get('irritability', ''),
            "emotional_numbness": responses.get('emotional_numbness', ''),
            "crying_episodes": responses.get('crying_spells', ''),
            "anxiety_with_depression": "not assessed",
            "emotional_pain": responses.get('mood_description', '')
        },
        "fatigue_assessment": {
            "fatigue_presence": responses.get('fatigue_present', ''),
            "fatigue_severity": responses.get('fatigue_severity', ''),
            "fatigue_pattern": responses.get('fatigue_pattern', ''),
            "energy_level_change": responses.get('fatigue_severity', ''),
            "morning_fatigue": "to be assessed",
            "afternoon_fatigue": "to be assessed",
            "physical_exhaustion": responses.get('fatigue_present', ''),
            "fatigue_worsening_factors": responses.get('fatigue_factors', ''),
            "fatigue_improving_factors": responses.get('fatigue_factors', ''),
            "fatigue_impact_daily_life": responses.get('fatigue_impact', ''),
            "impact_on_work_school": responses.get('work_function', ''),
            "impact_on_social": responses.get('social_function', ''),
            "impact_on_self_care": responses.get('self_care', ''),
            "fatigue_distinct_from_sadness": "combined presentation"
        },
        "restlessness_assessment": {
            "restlessness_presence": responses.get('restlessness', ''),
            "restlessness_type": responses.get('restlessness_type', ''),
            "restlessness_severity": responses.get('restlessness_severity', ''),
            "agitation_level": responses.get('restlessness_severity', ''),
            "physical_manifestations": responses.get('restlessness_type', ''),
            "restlessness_pattern": "throughout day",
            "sense_of_urgency": "not assessed",
            "racing_thoughts": "not assessed",
            "sleep_impact": "to be assessed",
            "daily_function_impact": responses.get('restlessness_impact', ''),
            "work_impact": responses.get('work_function', ''),
            "relationship_impact": responses.get('social_function', ''),
            "restlessness_vs_anxiety": "depression-related agitation",
            "attempts_to_manage": "not assessed"
        },
        "concentration_assessment": {
            "concentration_difficulty": responses.get('concentration_difficulty', ''),
            "concentration_pattern": "constant based on patient report",
            "attention_span": responses.get('concentration_examples', ''),
            "specific_task_difficulty": responses.get('concentration_examples', ''),
            "mind_wandering": "not specifically assessed",
            "forgetfulness": "not specifically assessed",
            "decision_making": "not specifically assessed",
            "work_school_impact": responses.get('concentration_impact', ''),
            "reading_comprehension": "not specifically assessed",
            "conversation_engagement": "not specifically assessed",
            "task_completion": responses.get('concentration_impact', ''),
            "mental_effort_required": responses.get('concentration_severity', ''),
            "time_perception": "not assessed",
            "concentration_worse_morning_evening": "not assessed",
            "triggers_concentration_loss": responses.get('concentration_examples', ''),
            "concentration_improving_factors": "not assessed",
            "concentration_vs_mood": "depression-related"
        },
        "cognitive_symptoms": {
            "hopelessness": "not specifically assessed",
            "worthlessness": "not specifically assessed",
            "self_criticism": "not specifically assessed",
            "rumination": "not specifically assessed",
            "death_thoughts": responses.get('suicidal_thoughts', ''),
            "suicidal_ideation": responses.get('suicidal_thoughts', '')
        },
        "suicide_risk_assessment": {
            "suicidal_thoughts_presence": responses.get('suicidal_thoughts', ''),
            "suicidal_intent": responses.get('suicide_intent', ''),
            "suicide_plan_specificity": responses.get('suicide_plan', ''),
            "protective_factors": responses.get('social_support', ''),
            "past_suicide_attempts": "not assessed",
            "current_access_to_means": responses.get('suicide_means', ''),
            "risk_level": "high" if responses.get('suicidal_thoughts') == 'yes' else "low",
            "crisis_intervention_needed": "yes" if responses.get('suicidal_thoughts') == 'yes' else "no"
        },
        "motivation_and_functioning": {
            "motivation_loss": responses.get('motivation_loss', ''),
            "psychomotor_retardation": "not assessed",
            "psychomotor_agitation": responses.get('restlessness', ''),
            "work_school_function": responses.get('work_function', ''),
            "social_function": responses.get('social_function', ''),
            "self_care": responses.get('self_care', ''),
            "withdrawal_isolation": responses.get('social_function', '')
        },
        "sleep_and_appetite": {
            "sleep_insomnia": responses.get('sleep_changes', ''),
            "sleep_hypersomnia": responses.get('sleep_changes', ''),
            "sleep_quality": responses.get('sleep_changes', ''),
            "sleep_pattern_change": "yes" if responses.get('sleep_changes') else "no",
            "appetite_loss": responses.get('appetite_changes', ''),
            "appetite_increase": responses.get('appetite_changes', ''),
            "appetite_pattern_change": "yes" if responses.get('appetite_changes') else "no",
            "weight_change": responses.get('appetite_changes', ''),
            "nutritional_status": "not assessed"
        },
        "social_and_relationships": {
            "social_support": responses.get('social_support', ''),
            "relationship_quality": responses.get('social_function', ''),
            "loneliness": "not specifically assessed",
            "burden_to_others": "not assessed",
            "interpersonal_effectiveness": responses.get('social_function', '')
        },
        "duration_and_course": {
            "episode_onset": responses.get('symptom_onset', ''),
            "episode_duration": "past 2 weeks and ongoing",
            "previous_episodes": responses.get('previous_episodes', ''),
            "seasonal_pattern": "not assessed",
            "triggers_identified": responses.get('recent_stressors', ''),
            "remission_pattern": "not assessed"
        },
        "medical_and_contextual_factors": {
            "past_psychiatric_history": responses.get('previous_episodes', ''),
            "family_psychiatric_history": responses.get('family_history', ''),
            "medical_conditions": "not assessed",
            "medications_affect_mood": responses.get('current_medications', ''),
            "substance_use_impact": "not assessed",
            "life_stressors": responses.get('recent_stressors', ''),
            "trauma_history": "not assessed",
            "sleep_deprivation": responses.get('sleep_changes', '')
        },
        "prior_treatment_history": {
            "previous_antidepressants": responses.get('previous_treatment_type', ''),
            "previous_psychotherapy": responses.get('previous_treatment_type', ''),
            "previous_hospitalization": "not assessed",
            "treatment_compliance": "not assessed",
            "current_treatment": responses.get('current_treatment', '')
        },
        "assessment_summary": {
            "depression_screening_result": "probable depression" if responses.get('depressed_mood') == 'yes' and responses.get('anhedonia') == 'yes' else "possible depression" if responses.get('depressed_mood') == 'yes' or responses.get('anhedonia') == 'yes' else "negative",
            "depression_severity": "To be determined by clinician",
            "core_symptoms_present": "both" if responses.get('depressed_mood') == 'yes' and responses.get('anhedonia') == 'yes' else "one or none",
            "symptom_count": "Multiple symptoms reported",
            "prominent_symptoms": f"{', '.join([k for k, v in responses.items() if v in ['yes', 'severe', 'extreme', 'moderate']])}",
            "functional_impairment": responses.get('work_function', ''),
            "suicide_risk": "high" if responses.get('suicidal_thoughts') == 'yes' else "low",
            "depression_type": "To be determined by clinician",
            "comorbid_conditions": "Not assessed",
            "protective_strengths": responses.get('social_support', ''),
            "recommendations": "Psychiatric evaluation recommended",
            "specialist_referral": "Psychiatry/Psychology referral indicated"
        }
    }

    # Create assessment object
    assessment = DepressionScreeningAssessment(**assessment_data)

    # Save to file
    if output_path is None:
        output_path = Path("outputs") / f"{patient_name.lower().replace(' ', '_')}_depression_screening.json"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        json.dump(assessment.model_dump(), f, indent=2)

    print(f"\n✓ Depression screening assessment saved to: {output_path}")

    return assessment


def evaluate_depression_screening(
    patient_name: str,
    output_path: Optional[Path] = None,
    use_schema_prompt: bool = True,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
) -> DepressionScreeningAssessment:
    """
    Conduct depression screening assessment for a patient through interactive questioning.

    Args:
        patient_name: Name or identifier of the patient
        output_path: Optional path to save JSON output. Defaults to outputs/{patient_name}_depression_screening.json
        use_schema_prompt: Whether to use PydanticPromptGenerator for schema
        prompt_style: Style of schema prompt (DETAILED, CONCISE, TECHNICAL)
        client: Optional MedKitClient for LLM-generated questions
        patient_context: Optional patient-specific context for personalized questions

    Returns:
        DepressionScreeningAssessment: Validated depression screening assessment object
    """
    if not patient_name or not patient_name.strip():
        raise ValueError("Patient name cannot be empty")

    print(f"\nStarting depression screening assessment for: {patient_name}")

    # Ask patient questions interactively
    responses = ask_depression_screening_questions(client=client, patient_context=patient_context, prompt_style=prompt_style)

    # Create assessment from responses
    assessment = create_depression_assessment_from_responses(patient_name, responses, output_path)

    return assessment


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description="Conduct depression screening assessment for a patient",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default - saves to outputs/patient_depression_screening.json
  python exam_depression_screening.py "John Doe"

  # Custom output path
  python exam_depression_screening.py "John Doe" -o custom_assessment.json

  # With concise prompting
  python exam_depression_screening.py "John Doe" --concise

Depression Screening Protocol:
  1. CORE SCREENING QUESTIONS (2-week timeframe):
     - Over the past 2 weeks, have you felt down, depressed, or hopeless?
     - Over the past 2 weeks, have you felt little interest or pleasure in doing things?
     EXPECTED: Negative response to one or both
     UNEXPECTED: Positive response to both indicates depression risk

  2. FATIGUE AND LOSS OF ENERGY:
     - Have you felt constantly tired or lacking energy?
     - Is it mild, moderate, or severe?
     - When during the day is fatigue worst?
     - How much does it interfere with work, social life, self-care?
     - What makes it better or worse?

  3. RESTLESSNESS AND AGITATION:
     - Have you felt restless or unable to sit still?
     - Do you fidget, pace, or feel agitated?
     - How severe is it? Observable by others?
     - Does it interfere with sleep or daily activities?
     - How is this different from your usual self?

  4. POOR CONCENTRATION AND DIFFICULTY THINKING:
     - Have you had trouble concentrating or focusing?
     - Can you read, work, follow conversations?
     - Is your mind wandering or racing?
     - How long can you focus before losing attention?
     - What impact on work, school, daily tasks?

  5. MOOD AND EMOTION:
     - Describe your mood over the past 2 weeks
     - Any irritability, crying spells, or emotional numbness?
     - Rate sadness/emptiness on 0-10 scale

  6. CRITICAL - SUICIDE RISK:
     - Have you thought about harming yourself?
     - Do you have a plan? Access to means?
     - Any past suicide attempts?
     ALERT: If positive ideation with plan/intent → immediate safety assessment

  7. PHYSICAL AND FUNCTIONAL:
     - Changes in sleep, appetite, energy level?
     - Ability to work, socialize, self-care?

  8. TIMELINE AND HISTORY:
     - When did symptoms start?
     - Any previous depressive episodes?
     - Family history of depression?

  9. TREATMENTS:
     - Previous antidepressants or therapy?
     - Current treatments?
        """
    )
    parser.add_argument("patient", nargs='*', default=['unknown'], help="Name or identifier of the patient (default: 'unknown')")
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Path to save JSON output. Defaults to outputs/{patient_name}_depression_screening.json"
    )
    parser.add_argument(
        "--concise",
        action="store_true",
        help="Use concise prompt style (faster generation)"
    )

    args = parser.parse_args()

    try:
        patient_name = " ".join(args.patient)
        prompt_style = PromptStyle.CONCISE if args.concise else PromptStyle.DETAILED

        result = evaluate_depression_screening(
            patient_name=patient_name,
            output_path=args.output,
            prompt_style=prompt_style,
        )
        print("✓ Success!")

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
