"""
Blood Vessels Vascular Assessment

Evaluate patient vascular system through structured examination including
blood pressure, pulses, skin inspection, and symptom assessment
using BaseModel definitions and the MedKit AI client with schema-aware prompting.
"""

import sys
import json
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

# Fix import paths
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.pydantic_prompt_generator import PromptStyle
from core.medkit_client import MedKitClient


class VascularQuestion(BaseModel):
    """A single vascular assessment question with guidance."""
    question_number: int = Field(description="Question number")
    question_text: str = Field(description="The vascular examination question to ask the patient")
    assessment_domain: str = Field(description="Domain being assessed (e.g., pain, swelling, pulses)")
    clinical_significance: str = Field(description="Why this question matters clinically")
    follow_up_guidance: str = Field(description="How to follow up on responses")


class VascularTestQuestions(BaseModel):
    """Dynamic vascular assessment questions generated by LLM."""
    questions: List[VascularQuestion] = Field(description="List of vascular assessment questions")
    assessment_context: str = Field(description="Clinical context for vascular assessment")


class PatientSymptoms(BaseModel):
    """Patient-reported vascular symptoms."""
    limb_pain: str = Field(description="Any limb pain, cramping, or claudication with walking")
    swelling: str = Field(description="Any swelling in legs or arms")
    coldness: str = Field(description="Do hands or feet feel cold or numb")
    color_changes: str = Field(description="Any color changes in skin: pale, cyanotic, red")
    varicosities: str = Field(description="Any visible varicose veins or bulging veins")
    ulcers: str = Field(description="Any ulcers or non-healing wounds on legs or feet")
    thrombosis_history: str = Field(description="History of deep vein thrombosis or pulmonary embolism")
    risk_factors: str = Field(description="Any hypertension, diabetes, hyperlipidemia, smoking")


class PhysicalExamination(BaseModel):
    """Physical examination findings."""
    blood_pressure: str = Field(description="Blood pressure measurements (systolic/diastolic)")
    radial_pulses: str = Field(description="Radial pulse assessment (strength, symmetry)")
    femoral_pulses: str = Field(description="Femoral pulse assessment")
    popliteal_pulses: str = Field(description="Popliteal pulse assessment")
    dorsalis_pedis_pulses: str = Field(description="Dorsalis pedis pulse assessment")
    posterior_tibial_pulses: str = Field(description="Posterior tibial pulse assessment")
    skin_inspection: str = Field(description="Skin color, temperature, edema, ulcers")
    carotid_auscultation: str = Field(description="Carotid artery auscultation for bruits")
    femoral_auscultation: str = Field(description="Femoral artery auscultation for bruits")
    ankle_brachial_index: str = Field(description="Ankle-brachial index if measured")
    extremity_measurements: str = Field(description="Limb circumference measurements if taken")


class VascularRiskFactors(BaseModel):
    """Assessment of vascular risk factors."""
    hypertension: str = Field(description="History of hypertension - none/controlled/uncontrolled")
    diabetes: str = Field(description="History of diabetes - none/type 1/type 2/controlled/uncontrolled")
    hyperlipidemia: str = Field(description="History of high cholesterol - none/yes/controlled/uncontrolled")
    smoking_status: str = Field(description="Smoking status - never/former/current/quantity")
    family_history: str = Field(description="Family history of vascular disease - none/yes/specific details")
    obesity: str = Field(description="BMI/obesity status - normal/overweight/obese")
    physical_activity: str = Field(description="Physical activity level - sedentary/light/moderate/vigorous")
    antiplatelet_therapy: str = Field(description="Use of antiplatelet medications - none/aspirin/clopidogrel/other")


class VascularAssessmentSummary(BaseModel):
    """Overall vascular assessment findings and clinical recommendations."""
    vascular_status: str = Field(description="Overall vascular status - normal/low-risk/moderate-risk/high-risk")
    symptom_severity: str = Field(description="Severity of vascular symptoms - none/mild/moderate/severe")
    pulse_assessment: str = Field(description="Overall pulse assessment - normal/diminished/asymmetric/absent")
    skin_findings: str = Field(description="Significant skin findings - none/edema/color changes/ulcers")
    identified_risks: str = Field(description="Identified vascular risk factors, comma-separated")
    acute_concerns: str = Field(description="Any acute vascular concerns - none/possible/probable/definite")
    imaging_recommendations: str = Field(description="Recommended imaging (Doppler, CT, angiography, etc.)")
    specialist_referral: str = Field(description="Whether cardiology or vascular surgery referral recommended")
    follow_up_plan: str = Field(description="Recommended follow-up plan and timeline")
    patient_education: str = Field(description="Patient education provided regarding risk factors")


class BloodVesselsAssessment(BaseModel):
    """
    Comprehensive vascular system assessment.

    Organized as a collection of BaseModel sections, each representing
    distinct aspects of vascular evaluation. Includes patient symptoms,
    physical examination findings, risk factor assessment, and clinical summary.
    """
    # Patient-reported symptoms
    patient_symptoms: PatientSymptoms

    # Physical examination findings
    physical_examination: PhysicalExamination

    # Vascular risk factors
    risk_factors: VascularRiskFactors

    # Final assessment summary
    assessment_summary: VascularAssessmentSummary


def generate_vascular_questions(
    client: MedKitClient,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> VascularTestQuestions:
    """
    Generate vascular assessment questions using LLM.

    Args:
        client: MedKitClient instance for LLM generation
        patient_context: Optional patient context for question generation
        prompt_style: Style of prompt generation (DETAILED, CONCISE, TECHNICAL)

    Returns:
        VascularTestQuestions with LLM-generated vascular assessment questions
    """
    context_note = f"\nPatient context: {patient_context}" if patient_context else ""

    subject = f"""Generate comprehensive vascular system assessment questions covering these domains:
1. Patient symptoms (pain, swelling, coldness, color changes, ulcers)
2. Vascular history (claudication, thrombosis, varicose veins)
3. Risk factors (hypertension, diabetes, smoking, hyperlipidemia)
4. Physical findings (pulses, bruits, skin changes)
5. Functional impact (walking distance, daily activities)
6. Medication history (antiplatelet, anticoagulant use)

Questions should be practical, testable in a clinical setting, and appropriate for vascular assessment.
Include clinical significance and follow-up guidance for each question.{context_note}"""

    sys_prompt = """You are an expert cardiologist and vascular surgeon. Vascular system assessment is crucial in clinical evaluation.

Generate structured clinical questions that are:
- Practical and testable in a clinical setting
- Appropriate for vascular assessment
- Including clinical significance and follow-up guidance
- Adhering to current medical standards and guidelines

Return structured JSON matching the exact schema provided, with all required fields populated."""

    return client.generate_text(
        prompt=subject,
        schema=VascularTestQuestions,
        sys_prompt=sys_prompt,
    )


def ask_vascular_questions(
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> dict:
    """
    Ask patient vascular assessment questions interactively and collect responses.

    If client is provided, uses LLM to generate dynamic questions.
    Otherwise, uses fallback hardcoded questions.

    Args:
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization
        prompt_style: Style of prompt generation

    Returns:
        Dictionary of patient responses to vascular questions
    """
    print("\n" + "="*60)
    print("VASCULAR ASSESSMENT")
    print("="*60)
    print()
    print("MEASURES: This assessment evaluates the patient's peripheral vascular health,")
    print("  circulation, and risk factors for vascular disease.")
    print("  • Peripheral pulse strength and symmetry")
    print("  • Claudication symptoms and pain with walking")
    print("  • Color changes, temperature, and capillary refill")
    print("  • Venous insufficiency signs (edema, varicosities)")
    print("  • Risk factors for arterial and venous disease")
    print()
    print("TOP 10 KEY ASSESSMENT QUESTIONS:")
    print("  1. Do you experience leg pain when walking that improves with rest?")
    print("  2. Have you noticed any color changes in your legs or feet?")
    print("  3. Do your legs or feet feel cold compared to the rest of your body?")
    print("  4. Do you have any swelling in your legs, ankles, or feet?")
    print("  5. Have you noticed any varicose veins?")
    print("  6. Do you have a history of blood clots (DVT or PE)?")
    print("  7. Do you smoke or have you smoked in the past?")
    print("  8. Do you have diabetes, high blood pressure, or high cholesterol?")
    print("  9. Do you have any non-healing wounds on your legs or feet?")
    print(" 10. Do you experience numbness or tingling in your extremities?")
    print()
    print("="*60)
    print("DETAILED VASCULAR QUESTIONNAIRE")
    print("="*60)

    responses = {}

    # Generate questions via LLM if client provided
    if client:
        print("\nGenerating vascular assessment questions...")
        try:
            vascular_qs = generate_vascular_questions(client, patient_context, prompt_style)
            print("\n" + "="*60)
            print("VASCULAR ASSESSMENT QUESTIONS")
            print("="*60)

            for q in vascular_qs.questions:
                print(f"\nDomain: {q.assessment_domain}")
                print(f"Clinical Significance: {q.clinical_significance}")
                response = input(f"{q.question_number}. {q.question_text}\n> ").strip()
                responses[f'q{q.question_number}_vascular'] = response
                print(f"   [Follow-up: {q.follow_up_guidance}]\n")
        except Exception as e:
            print(f"Warning: Could not generate questions via LLM: {e}")
            print("Using fallback questions...\n")

    # If no LLM generated questions, use fallback
    if not any(k.startswith('q') for k in responses.keys()):
        print("\n" + "="*60)
        print("VASCULAR ASSESSMENT QUESTIONS (Fallback)")
        print("="*60)

        responses['limb_pain'] = input("Any limb pain, cramping, or claudication with walking?: ").strip()
        responses['swelling'] = input("Any swelling in legs or arms?: ").strip()
        responses['coldness'] = input("Do hands or feet feel cold or numb?: ").strip()
        responses['color_changes'] = input("Any color changes in skin (pale, cyanotic, red)?: ").strip()
        responses['varicosities'] = input("Any visible varicose veins or bulging veins?: ").strip()
        responses['ulcers'] = input("Any ulcers or non-healing wounds on legs or feet?: ").strip()
        responses['thrombosis_history'] = input("History of deep vein thrombosis or pulmonary embolism?: ").strip()
        responses['risk_factors'] = input("Any hypertension, diabetes, hyperlipidemia, or smoking?: ").strip()

    # PHYSICAL EXAMINATION
    print("\n" + "="*60)
    print("PHYSICAL EXAMINATION")
    print("="*60)

    responses['blood_pressure'] = input("Blood pressure (systolic/diastolic): ").strip()
    responses['radial_pulses'] = input("Radial pulses (strength, symmetry): ").strip()
    responses['femoral_pulses'] = input("Femoral pulses assessment: ").strip()
    responses['popliteal_pulses'] = input("Popliteal pulses assessment: ").strip()
    responses['dorsalis_pedis'] = input("Dorsalis pedis pulses assessment: ").strip()
    responses['posterior_tibial'] = input("Posterior tibial pulses assessment: ").strip()
    responses['skin_inspection'] = input("Skin inspection findings (color, temperature, edema, ulcers): ").strip()
    responses['carotid_auscultation'] = input("Carotid artery auscultation for bruits: ").strip()
    responses['femoral_auscultation'] = input("Femoral artery auscultation for bruits: ").strip()
    responses['ankle_brachial_index'] = input("Ankle-brachial index if measured: ").strip()
    responses['extremity_measurements'] = input("Limb circumference measurements if taken: ").strip()

    # RISK FACTORS
    print("\n" + "="*60)
    print("VASCULAR RISK FACTORS")
    print("="*60)

    responses['hypertension'] = input("History of hypertension (none/controlled/uncontrolled): ").strip()
    responses['diabetes'] = input("History of diabetes (none/type 1/type 2/status): ").strip()
    responses['hyperlipidemia'] = input("History of high cholesterol (none/yes/status): ").strip()
    responses['smoking_status'] = input("Smoking status (never/former/current/quantity): ").strip()
    responses['family_history'] = input("Family history of vascular disease: ").strip()
    responses['obesity'] = input("BMI/obesity status: ").strip()
    responses['physical_activity'] = input("Physical activity level: ").strip()
    responses['antiplatelet_therapy'] = input("Use of antiplatelet medications: ").strip()

    return responses


def create_vascular_assessment_from_responses(
    patient_name: str,
    responses: dict,
    output_path: Optional[Path] = None
) -> BloodVesselsAssessment:
    """
    Create a structured vascular assessment object from collected patient responses.

    Args:
        patient_name: Name of the patient
        responses: Dictionary of patient responses from questions
        output_path: Optional path to save JSON output

    Returns:
        BloodVesselsAssessment: Validated assessment object
    """
    assessment_data = {
        "patient_symptoms": {
            "limb_pain": responses.get('limb_pain', ''),
            "swelling": responses.get('swelling', ''),
            "coldness": responses.get('coldness', ''),
            "color_changes": responses.get('color_changes', ''),
            "varicosities": responses.get('varicosities', ''),
            "ulcers": responses.get('ulcers', ''),
            "thrombosis_history": responses.get('thrombosis_history', ''),
            "risk_factors": responses.get('risk_factors', '')
        },
        "physical_examination": {
            "blood_pressure": responses.get('blood_pressure', ''),
            "radial_pulses": responses.get('radial_pulses', ''),
            "femoral_pulses": responses.get('femoral_pulses', ''),
            "popliteal_pulses": responses.get('popliteal_pulses', ''),
            "dorsalis_pedis_pulses": responses.get('dorsalis_pedis', ''),
            "posterior_tibial_pulses": responses.get('posterior_tibial', ''),
            "skin_inspection": responses.get('skin_inspection', ''),
            "carotid_auscultation": responses.get('carotid_auscultation', ''),
            "femoral_auscultation": responses.get('femoral_auscultation', ''),
            "ankle_brachial_index": responses.get('ankle_brachial_index', ''),
            "extremity_measurements": responses.get('extremity_measurements', '')
        },
        "risk_factors": {
            "hypertension": responses.get('hypertension', ''),
            "diabetes": responses.get('diabetes', ''),
            "hyperlipidemia": responses.get('hyperlipidemia', ''),
            "smoking_status": responses.get('smoking_status', ''),
            "family_history": responses.get('family_history', ''),
            "obesity": responses.get('obesity', ''),
            "physical_activity": responses.get('physical_activity', ''),
            "antiplatelet_therapy": responses.get('antiplatelet_therapy', '')
        },
        "assessment_summary": {
            "vascular_status": "To be determined by clinician",
            "symptom_severity": "To be assessed",
            "pulse_assessment": "To be assessed by clinician",
            "skin_findings": "To be determined",
            "identified_risks": "To be identified by clinician",
            "acute_concerns": "None identified",
            "imaging_recommendations": "To be determined based on findings",
            "specialist_referral": "Not indicated at this time",
            "follow_up_plan": "Routine vascular assessment follow-up",
            "patient_education": "Standard vascular health education provided"
        }
    }

    # Create assessment object
    assessment = BloodVesselsAssessment(**assessment_data)

    # Save to file if path provided
    if output_path is None:
        output_path = Path("outputs") / f"{patient_name.lower().replace(' ', '_')}_vascular.json"

    # Create outputs directory if it doesn't exist
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save assessment as JSON
    with open(output_path, 'w') as f:
        json.dump(assessment.model_dump(), f, indent=2)

    print(f"\n✓ Assessment saved to: {output_path}")

    return assessment


def evaluate_vascular_system(
    patient_name: str,
    output_path: Optional[Path] = None,
    use_schema_prompt: bool = True,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
) -> BloodVesselsAssessment:
    """
    Evaluate patient vascular system through structured assessment.

    Args:
        patient_name: Name or identifier of the patient
        output_path: Optional path to save JSON output
        use_schema_prompt: Whether to use schema-aware prompting
        prompt_style: Style of prompt generation
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization

    Returns:
        BloodVesselsAssessment: Validated vascular assessment object
    """
    if not patient_name or not patient_name.strip():
        raise ValueError("Patient name cannot be empty")

    print(f"\nStarting vascular system assessment for: {patient_name}")
    responses = ask_vascular_questions(client, patient_context, prompt_style)

    assessment = create_vascular_assessment_from_responses(patient_name, responses, output_path)

    return assessment


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description="Evaluate patient vascular system through structured assessment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default - saves to outputs/unknown_vascular.json
  python exam_blood_vessels.py

  # With patient name
  python exam_blood_vessels.py "John Doe"

  # Custom output path
  python exam_blood_vessels.py "John Doe" -o custom_assessment.json

  # With concise prompting
  python exam_blood_vessels.py "John Doe" --concise

Vascular Assessment Protocol:
  1. PATIENT SYMPTOMS:
     - Limb pain, claudication with walking
     - Swelling in legs or arms
     - Coldness or numbness in extremities
     - Color changes (pale, cyanotic, red)
     - Varicose veins or bulging veins
     - Ulcers or non-healing wounds
     - History of thrombosis or embolism

  2. PHYSICAL EXAMINATION:
     - Blood pressure measurement
     - Pulse assessment (radial, femoral, popliteal, dorsalis pedis, posterior tibial)
     - Skin inspection (color, temperature, edema, ulcers)
     - Auscultation (carotid, femoral bruits)
     - Ankle-brachial index if available

  3. RISK FACTOR ASSESSMENT:
     - Hypertension, diabetes, hyperlipidemia
     - Smoking status
     - Family history
     - Physical activity level
        """
    )
    parser.add_argument("patient", nargs='*', default=['unknown'], help="Name or identifier of the patient (default: 'unknown')")
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Path to save JSON output. Defaults to outputs/{patient_name}_vascular.json"
    )
    parser.add_argument(
        "--concise",
        action="store_true",
        help="Use concise prompt style (faster generation)"
    )

    args = parser.parse_args()

    try:
        patient_name = " ".join(args.patient)
        prompt_style = PromptStyle.CONCISE if args.concise else PromptStyle.DETAILED

        result = evaluate_vascular_system(
            patient_name=patient_name,
            output_path=args.output,
            prompt_style=prompt_style,
        )
        print("✓ Success!")

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
