"""
Attention Span Assessment

Evaluate patient attention span and concentration capabilities through
command following, serial tasks, spelling tasks, and arithmetic calculations
using BaseModel definitions and the MedKit AI client with schema-aware prompting.
"""

import sys
import json
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional, List

# Fix import paths
sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.pydantic_prompt_generator import PromptStyle
from core.medkit_client import MedKitClient


class AttentionQuestion(BaseModel):
    """A single attention span assessment question with guidance."""
    question_number: int = Field(description="Question number")
    question_text: str = Field(description="The attention question to ask the patient")
    assessment_domain: str = Field(description="Domain being assessed (e.g., command following, spelling, arithmetic)")
    task_description: str = Field(description="Description of what the task measures")
    evaluation_criteria: str = Field(description="How to evaluate the patient's performance")


class AttentionTestQuestions(BaseModel):
    """Dynamic attention span assessment questions generated by LLM."""
    questions: List[AttentionQuestion] = Field(description="List of attention span test questions")
    assessment_context: str = Field(description="Clinical context for attention assessment")


class CommandFollowing(BaseModel):
    """Patient's ability to follow simple and complex commands."""
    single_step_command: str = Field(description="Ability to follow single-step commands (e.g., 'Close your eyes', 'Touch your nose'). Success rate and any misunderstandings")
    two_step_command: str = Field(description="Ability to follow two-step commands (e.g., 'Take off your glasses and put them on the table'). Accuracy and sequence maintenance")
    three_step_command: str = Field(description="Ability to follow three-step commands (e.g., 'Take off all clothes, put on patient gown, sit on examining table'). Order maintained/order confused/incomplete/unable")
    complex_command: str = Field(description="Ability to follow more complex commands with conditional elements or multiple operations. Accuracy and completeness")
    command_comprehension: str = Field(description="Understanding of commands - good/fair/requires repetition/requires simplification/unable to understand")
    response_latency: str = Field(description="Time between command and response - immediate/slight delay/significant delay/very delayed/no response")
    compliance_level: str = Field(description="Patient compliance with commands - fully compliant/mostly compliant/partially compliant/non-compliant/oppositional")
    perseveration: str = Field(description="Tendency to repeat or perseverate on previous commands - not present/mild/moderate/severe")
    distractibility_during_commands: str = Field(description="Distractibility observed during command following - not present/minimal/moderate/severe")


class SpellingTasks(BaseModel):
    """Patient's spelling abilities and attention during spelling tasks."""
    spell_world_forward: str = Field(description="Ability to spell 'WORLD' forward - correct/minor error/major error/unable. Note any letter transpositions or omissions")
    spell_world_backward: str = Field(description="Ability to spell 'WORLD' backward (D-L-R-O-W) - correct/minor error/major error/unable")
    spelling_accuracy_forward: str = Field(description="Overall accuracy of forward spelling - accurate/mostly accurate/inconsistent/impaired")
    spelling_accuracy_backward: str = Field(description="Overall accuracy of backward spelling - accurate/mostly accurate/inconsistent/impaired/severely impaired")
    spelling_speed_forward: str = Field(description="Speed of forward spelling - quick/normal/slow/very slow")
    spelling_speed_backward: str = Field(description="Speed of backward spelling - quick/normal/slow/very slow/unable to attempt")
    letter_sequencing: str = Field(description="Ability to maintain correct letter sequence - maintained/occasional reversals/frequent reversals/confused")
    spelling_effort: str = Field(description="Patient effort during spelling tasks - good/fair/poor/minimal/gave up")
    spelling_frustration: str = Field(description="Frustration or anxiety during spelling tasks - none/mild/moderate/severe")


class SerialTasks(BaseModel):
    """Patient's performance on serial tasks requiring sustained attention."""
    months_backward: str = Field(description="Ability to recite months backward from December - all correct/mostly correct/partial/unable. Note starting point and where stopped")
    days_backward: str = Field(description="Ability to recite days backward from Sunday - all correct/mostly correct/partial/unable")
    counting_backward: str = Field(description="Ability to count backward from 20 to 1 - accurate/mostly accurate/errors/unable. Note speed and accuracy")
    serial_sevens: str = Field(description="Ability to count backward by 7s from 100 (100, 93, 86, 79...) - accurate/mostly accurate/some errors/unable. How many correct")
    alphabet_recitation: str = Field(description="Ability to recite alphabet forward - accurate/minor errors/major errors/unable")
    task_completion_rate: str = Field(description="Ability to complete serial tasks - completes all/most tasks/some tasks/none")
    error_correction: str = Field(description="Ability to recognize and correct own errors - spontaneously/with prompting/not recognized/errors persist")
    task_switching: str = Field(description="Ability to switch between different serial tasks smoothly - smooth/effortful/confused/unable")


class ArithmeticAttention(BaseModel):
    """Assessment of attention span through arithmetic calculation tasks."""
    simple_arithmetic_focus: str = Field(description="Ability to focus on simple arithmetic without distraction - sustained focus/occasional lapses/frequent distractions/unable to focus")
    arithmetic_accuracy: str = Field(description="Accuracy of arithmetic calculations - accurate/mostly accurate/some errors/many errors")
    arithmetic_speed: str = Field(description="Speed of arithmetic calculation - quick/normal/slow/very slow")
    arithmetic_persistence: str = Field(description="Ability to persist with increasingly difficult arithmetic - maintains focus/decreases with difficulty/gives up/minimal attempt")
    serial_calculations: str = Field(description="Ability to perform serial arithmetic (multiple problems in sequence) - maintains accuracy/accuracy declines/loses focus/abandons task")
    mental_fatigue: str = Field(description="Evidence of mental fatigue during arithmetic - not evident/mild fatigue/moderate fatigue/severe fatigue")
    self_awareness_errors: str = Field(description="Awareness of errors made during arithmetic - recognizes errors/some awareness/limited awareness/unaware")


class SustainedAttention(BaseModel):
    """Assessment of sustained attention and concentration over time."""
    initial_focus: str = Field(description="Patient's focus at beginning of testing - excellent/good/fair/poor")
    focus_maintenance: str = Field(description="Ability to maintain focus throughout testing - consistent/gradually declines/fluctuates/poor throughout")
    attention_span_duration: str = Field(description="Estimated duration of sustained attention - >30 minutes/20-30 minutes/10-20 minutes/5-10 minutes/<5 minutes")
    fatigue_point: str = Field(description="Point during testing when fatigue or loss of attention becomes evident - early/mid-testing/late/does not occur")
    recovery_with_rest: str = Field(description="Ability to recover attention with brief rest or redirection - good recovery/partial recovery/limited recovery/no recovery")
    environmental_sensitivity: str = Field(description="Sensitivity to environmental distractions - minimal/moderate/significant. Specific distractions noted")
    task_persistence: str = Field(description="Willingness to persist with challenging tasks - high/moderate/low/gives up easily")
    motivation_level: str = Field(description="Apparent motivation during testing - high/moderate/low/variable/minimal effort")


class SelectiveAttention(BaseModel):
    """Assessment of selective attention - ability to focus on relevant stimuli."""
    target_detection: str = Field(description="Ability to detect target stimuli among distractors - excellent/good/fair/poor")
    irrelevant_stimulus_filtering: str = Field(description="Ability to ignore irrelevant stimuli - filters well/some difficulty/significant difficulty/unable to filter")
    background_noise_impact: str = Field(description="Impact of background noise or activity on performance - minimal/moderate/significant")
    competing_stimuli_performance: str = Field(description="Performance when competing demands present - maintains focus/divided attention/loses focus/unable to manage")
    selective_attention_speed: str = Field(description="Speed of response when selective attention required - normal/slower than normal/significantly slower")


class ConcentrationDifficulties(BaseModel):
    """Documentation of specific concentration difficulties and attention lapses."""
    attention_lapses: str = Field(description="Frequency of attention lapses or mind wandering - not observed/occasional/frequent/constant")
    lapse_duration: str = Field(description="Duration of attention lapses when they occur - brief (seconds)/moderate (minutes)/extended/unclear")
    mind_wandering_content: str = Field(description="Content of mind wandering when it occurs - worries/random thoughts/physical discomfort/external environment")
    attention_shifting_difficulty: str = Field(description="Difficulty shifting attention between tasks - no difficulty/mild difficulty/moderate difficulty/severe difficulty")
    hyperactivity_observed: str = Field(description="Hyperactivity or restlessness observed - not present/mild/moderate/severe")
    impulsivity_level: str = Field(description="Impulsivity (acting without thinking) - not present/occasional/frequent/severe")
    distractibility_severity: str = Field(description="Overall severity of distractibility - minimal/mild/moderate/severe")


class CognitiveLimitations(BaseModel):
    """Assessment of underlying cognitive limitations affecting attention."""
    adhd_indicators: str = Field(description="Indicators of ADHD (inattention, hyperactivity, impulsivity) - not present/possible/probable/consistent with ADHD")
    frontal_lobe_dysfunction: str = Field(description="Indicators of frontal lobe dysfunction (executive control, attention regulation) - not present/possible/probable/evident")
    working_memory_impact: str = Field(description="Impact of working memory limitations on attention - not present/mild/moderate/severe")
    processing_speed: str = Field(description="Slow processing speed affecting attention performance - not present/mild/moderate/severe")
    language_comprehension: str = Field(description="Language comprehension issues affecting attention to instructions - not present/yes/mild/severe")
    delirium_indicators: str = Field(description="Indicators of delirium or acute confusional state - not present/mild/moderate/severe")
    dementia_indicators: str = Field(description="Indicators of dementia affecting attention - not present/possible/probable/evident")


class ContextualFactors(BaseModel):
    """Consideration of contextual factors affecting attention performance."""
    sleep_quality: str = Field(description="Recent sleep quality and quantity - adequate/inadequate/poor. Impact on attention")
    fatigue_level: str = Field(description="Patient's fatigue level during testing - alert/mild fatigue/moderate fatigue/severe fatigue/exhausted")
    pain_or_discomfort: str = Field(description="Pain or physical discomfort affecting concentration - none/mild/moderate/severe")
    anxiety_level: str = Field(description="Anxiety or nervousness affecting attention - minimal/mild/moderate/severe")
    emotional_state: str = Field(description="Emotional state during testing - calm/anxious/depressed/frustrated/agitated/other")
    medications: str = Field(description="Current medications affecting attention - none/possible impact/known attention effects/sedating")
    substance_use: str = Field(description="Alcohol or substance use affecting concentration - not reported/possible/acknowledged/significant")
    testing_environment: str = Field(description="Appropriateness of testing environment - quiet and suitable/some distractions/noisy/unsuitable")
    previous_testing: str = Field(description="Patient's previous experience with cognitive testing - first time/previous experience/familiar with testing")


class AttentionSpanComparison(BaseModel):
    """Comparison of attention across different task types."""
    attention_during_commands: str = Field(description="Quality of attention during command following tasks - excellent/good/fair/poor")
    attention_during_spelling: str = Field(description="Quality of attention during spelling tasks - excellent/good/fair/poor")
    attention_during_arithmetic: str = Field(description="Quality of attention during arithmetic tasks - excellent/good/fair/poor")
    attention_during_serial_tasks: str = Field(description="Quality of attention during serial recitation tasks - excellent/good/fair/poor")
    relative_strengths: str = Field(description="Tasks or conditions where attention is relatively better - task types or characteristics")
    relative_weaknesses: str = Field(description="Tasks or conditions where attention is relatively worse - task types or characteristics")
    task_difficulty_effect: str = Field(description="Effect of task difficulty on attention - easier tasks better/minimal difference/harder tasks worse/severe deterioration with difficulty")


class AssessmentSummary(BaseModel):
    """Overall assessment findings and clinical recommendations."""
    attention_span_level: str = Field(description="Overall attention span and concentration level - normal/low-normal/mildly impaired/moderately impaired/severely impaired")
    sustained_attention_status: str = Field(description="Sustained attention ability - normal/low-normal/mildly impaired/moderately impaired/severely impaired")
    selective_attention_status: str = Field(description="Selective attention ability - normal/low-normal/mildly impaired/moderately impaired/severely impaired")
    concentration_quality: str = Field(description="Overall concentration quality - excellent/good/fair/poor")
    attention_strengths: str = Field(description="Identified attention strengths (areas of preserved attention), comma-separated")
    attention_weaknesses: str = Field(description="Identified attention weaknesses or deficits, comma-separated")
    distractibility_level: str = Field(description="Overall distractibility level - minimal/mild/moderate/severe")
    attention_disorder_indicators: str = Field(description="Whether attention disorder is indicated (ADHD, other) - not present/possible/probable/consistent")
    fatigue_impact: str = Field(description="Impact of fatigue on attention performance - minimal/mild/moderate/severe")
    contributing_factors: str = Field(description="Contributing factors to attention difficulties (sleep, anxiety, medications, etc.), comma-separated")
    recommendations: str = Field(description="Recommendations for attention support, environmental modifications, or further evaluation, comma-separated")
    specialist_referral: str = Field(description="Whether referral to neurology, neuropsychology, or psychiatry is recommended and rationale")


class AttentionSpanAssessment(BaseModel):
    """
    Comprehensive attention span and concentration assessment.

    Organized as a collection of BaseModel sections, each representing
    distinct aspects of attention function. Includes command following,
    spelling tasks (forward and backward), serial recitation tasks,
    arithmetic calculations, and sustained attention evaluation.
    """
    # Command following ability
    command_following: CommandFollowing

    # Spelling tasks (forward and backward)
    spelling_tasks: SpellingTasks

    # Serial tasks requiring attention
    serial_tasks: SerialTasks

    # Attention during arithmetic
    arithmetic_attention: ArithmeticAttention

    # Sustained attention over time
    sustained_attention: SustainedAttention

    # Selective attention
    selective_attention: SelectiveAttention

    # Concentration difficulties
    concentration_difficulties: ConcentrationDifficulties

    # Cognitive limitations affecting attention
    cognitive_limitations: CognitiveLimitations

    # Contextual factors
    contextual_factors: ContextualFactors

    # Comparison across task types
    attention_span_comparison: AttentionSpanComparison

    # Final assessment
    assessment_summary: AssessmentSummary


def generate_attention_questions(
    client: MedKitClient,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> AttentionTestQuestions:
    """
    Generate attention span assessment questions using LLM.

    Args:
        client: MedKitClient instance for LLM generation
        patient_context: Optional patient context for question generation
        prompt_style: Style of prompt generation (DETAILED, CONCISE, TECHNICAL)

    Returns:
        AttentionTestQuestions with LLM-generated attention assessment questions
    """
    context_note = f"\nPatient context: {patient_context}" if patient_context else ""

    subject = f"""Generate comprehensive attention span assessment questions covering these domains:
1. Command following (single, two-step, three-step, complex commands)
2. Spelling tasks (forward and backward spelling)
3. Serial tasks (reciting months/days backward, counting backward, serial 7s)
4. Arithmetic attention (calculations with focus and accuracy)
5. Sustained attention (focus maintenance, fatigue, recovery)
6. Selective attention (filtering distractions, competing stimuli)

Questions should be practical, testable in a clinical setting, and measure different aspects of attention.
Include evaluation criteria for each question.{context_note}"""

    sys_prompt = """You are an expert neuropsychologist specializing in attention assessment. Attention span and concentration assessment is crucial in clinical evaluation.

Generate structured clinical questions that are:
- Practical and testable in a clinical setting
- Measuring different aspects of attention
- Including evaluation criteria for each question
- Adhering to current medical standards and guidelines

Return structured JSON matching the exact schema provided, with all required fields populated."""

    return client.generate_text(
        prompt=subject,
        schema=AttentionTestQuestions,
        sys_prompt=sys_prompt,
    )


def ask_attention_span_questions(
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
) -> dict:
    """
    Ask patient attention span assessment questions interactively and collect responses.

    If client is provided, uses LLM to generate dynamic questions.
    Otherwise, uses fallback hardcoded questions.

    Args:
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization
        prompt_style: Style of prompt generation

    Returns:
        Dictionary of patient responses to attention questions
    """
    print("\n" + "="*60)
    print("ATTENTION SPAN ASSESSMENT")
    print("="*60)
    print()
    print("MEASURES: This assessment evaluates the patient's ability to focus, sustain attention,")
    print("  and perform tasks requiring concentration over time.")
    print("  • Ability to follow single-step and multi-step commands")
    print("  • Spelling tasks (forward and backward) requiring focus")
    print("  • Serial tasks like counting backward or reciting months")
    print("  • Arithmetic attention and mental calculation capabilities")
    print("  • Sustained and selective attention over time")
    print()
    print("TOP 10 KEY ASSESSMENT QUESTIONS:")
    print("  1. Can you follow this three-step command: Take off glasses, put on table, sit down?")
    print("  2. Spell 'WORLD' forward for me.")
    print("  3. Now spell 'WORLD' backward.")
    print("  4. Can you recite the months backward from December?")
    print("  5. Count backward from 20 to 1.")
    print("  6. Count backward by 7s from 100 (serial sevens).")
    print("  7. Can you recite the alphabet forward?")
    print("  8. How long can you typically focus on a task?")
    print("  9. Do you get easily distracted by background noise?")
    print(" 10. Do you notice your mind wandering during conversations?")
    print()
    print("="*60)
    print("DETAILED ATTENTION SPAN QUESTIONNAIRE")
    print("="*60)

    responses = {}

    # Generate questions via LLM if client provided
    if client:
        print("\nGenerating attention span test questions...")
        try:
            attention_qs = generate_attention_questions(client, patient_context, prompt_style)
            print("\n" + "="*60)
            print("ATTENTION SPAN TEST QUESTIONS")
            print("="*60)

            for q in attention_qs.questions:
                print(f"\nDomain: {q.assessment_domain}")
                print(f"Task: {q.task_description}")
                response = input(f"{q.question_number}. {q.question_text}\n> ").strip()
                responses[f'q{q.question_number}_attention'] = response
                print(f"   [Evaluation: {q.evaluation_criteria}]\n")
        except Exception as e:
            print(f"Warning: Could not generate questions via LLM: {e}")
            print("Using fallback questions...\n")

    # COMMAND FOLLOWING
    print("\n--- COMMAND FOLLOWING ---")
    print("I'll give you instructions to follow.")

    responses['single_step'] = input("Close your eyes. [Note if patient complies]: ").strip()
    responses['two_step'] = input("Take off your glasses and put them on the table. [Note if completed in order]: ").strip()
    responses['three_step'] = input("Touch your nose, then your left ear, then your right shoulder. [Note completion]: ").strip()
    responses['command_comprehension'] = input("Did you understand all the commands? (yes/no/mostly): ").strip()

    # SPELLING TASKS
    print("\n--- SPELLING TASKS ---")
    responses['spell_world_forward'] = input("Please spell 'WORLD' forward, letter by letter: ").strip()
    responses['spell_world_backward'] = input("Now spell 'WORLD' backward, letter by letter: ").strip()
    responses['spelling_difficulty'] = input("Was backward spelling harder than forward? (no/slightly/moderately/significantly): ").strip()

    # SERIAL TASKS
    print("\n--- SERIAL TASKS ---")
    responses['months_backward'] = input("Can you say the months of the year backward starting from December? (Try and list what you say): ").strip()
    responses['count_backward_20'] = input("Count backward from 20 to 1 as quickly and accurately as you can: ").strip()
    responses['serial_sevens'] = input("Count backward by 7s from 100 (100, 93, 86...). How far can you go?: ").strip()

    # ARITHMETIC ATTENTION
    print("\n--- ARITHMETIC ATTENTION ---")
    responses['math_1'] = input("What is 7 + 5? ").strip()
    responses['math_2'] = input("What is 25 - 8? ").strip()
    responses['math_3'] = input("What is 9 × 6? ").strip()
    responses['math_4'] = input("What is 48 ÷ 6? ").strip()
    responses['arithmetic_confidence'] = input("How confident were you about these calculations? (very/somewhat/unsure/guessing): ").strip()

    # SUSTAINED ATTENTION
    print("\n--- SUSTAINED ATTENTION ---")
    responses['focus_during_test'] = input("How well could you maintain focus throughout these tasks? (excellent/good/fair/poor): ").strip()
    responses['fatigue_noticed'] = input("Did you feel mentally fatigued during testing? (no/minimal/moderate/significant): ").strip()
    responses['distraction_level'] = input("Were you easily distracted by the surroundings? (no/minimally/moderately/very much): ").strip()

    # CONTEXTUAL FACTORS
    print("\n--- CONTEXTUAL FACTORS ---")
    responses['sleep_last_night'] = input("How well did you sleep last night? (well/okay/poorly): ").strip()
    responses['current_pain'] = input("Do you have any pain or physical discomfort right now? (no/mild/moderate/severe): ").strip()
    responses['anxiety_level'] = input("How anxious do you feel during this assessment? (not at all/slightly/moderately/very): ").strip()
    responses['current_medications'] = input("Are you on any medications? If yes, which ones affect alertness?: ").strip()

    return responses


def create_attention_assessment_from_responses(patient_name: str, responses: dict, output_path: Optional[Path] = None) -> AttentionSpanAssessment:
    """
    Create a structured attention span assessment object from collected patient responses.

    Args:
        patient_name: Name of the patient
        responses: Dictionary of patient responses from questions
        output_path: Optional path to save JSON output

    Returns:
        AttentionSpanAssessment: Validated assessment object
    """
    # Create assessment object from responses
    assessment_data = {
        "command_following": {
            "single_step_command": responses.get('single_step', ''),
            "two_step_command": responses.get('two_step', ''),
            "three_step_command": responses.get('three_step', ''),
            "complex_command": "Not tested",
            "command_comprehension": responses.get('command_comprehension', ''),
            "response_latency": "immediate",
            "compliance_level": "To be assessed by clinician",
            "perseveration": "Not observed",
            "distractibility_during_commands": "To be assessed by clinician"
        },
        "spelling_tasks": {
            "spell_world_forward": responses.get('spell_world_forward', ''),
            "spell_world_backward": responses.get('spell_world_backward', ''),
            "spelling_accuracy_forward": "To be assessed by clinician",
            "spelling_accuracy_backward": "To be assessed by clinician",
            "spelling_speed_forward": "normal",
            "spelling_speed_backward": responses.get('spelling_difficulty', ''),
            "letter_sequencing": "To be assessed by clinician",
            "spelling_effort": "Good effort",
            "spelling_frustration": "Not noted"
        },
        "serial_tasks": {
            "months_backward": responses.get('months_backward', ''),
            "days_backward": "Not tested",
            "counting_backward": responses.get('count_backward_20', ''),
            "serial_sevens": responses.get('serial_sevens', ''),
            "alphabet_recitation": "Not tested",
            "task_completion_rate": "To be assessed by clinician",
            "error_correction": "To be assessed by clinician",
            "task_switching": "To be assessed by clinician"
        },
        "arithmetic_attention": {
            "simple_arithmetic_focus": responses.get('focus_during_test', ''),
            "arithmetic_accuracy": "To be assessed by clinician",
            "arithmetic_speed": "normal",
            "arithmetic_persistence": "Completed all tasks",
            "serial_calculations": f"7+5={responses.get('math_1', '')}, 25-8={responses.get('math_2', '')}, 9×6={responses.get('math_3', '')}, 48÷6={responses.get('math_4', '')}",
            "mental_fatigue": responses.get('fatigue_noticed', ''),
            "self_awareness_errors": "To be assessed by clinician"
        },
        "sustained_attention": {
            "initial_focus": "Alert and attentive",
            "focus_maintenance": responses.get('focus_during_test', ''),
            "attention_span_duration": "duration of test completed",
            "fatigue_point": responses.get('fatigue_noticed', ''),
            "recovery_with_rest": "Not tested",
            "environmental_sensitivity": responses.get('distraction_level', ''),
            "task_persistence": "Good persistence demonstrated",
            "motivation_level": "Good motivation"
        },
        "selective_attention": {
            "target_detection": "To be assessed by clinician",
            "irrelevant_stimulus_filtering": responses.get('distraction_level', ''),
            "background_noise_impact": "To be assessed by clinician",
            "competing_stimuli_performance": "To be assessed by clinician",
            "selective_attention_speed": "normal"
        },
        "concentration_difficulties": {
            "attention_lapses": responses.get('distraction_level', ''),
            "lapse_duration": "Not quantified",
            "mind_wandering_content": "Not explored",
            "attention_shifting_difficulty": "Not explored",
            "hyperactivity_observed": "Not noted",
            "impulsivity_level": "Not assessed",
            "distractibility_severity": responses.get('distraction_level', '')
        },
        "cognitive_limitations": {
            "adhd_indicators": "To be assessed by clinician",
            "frontal_lobe_dysfunction": "Not indicated",
            "working_memory_impact": "To be assessed by clinician",
            "processing_speed": "Normal",
            "language_comprehension": "Adequate",
            "delirium_indicators": "Not indicated",
            "dementia_indicators": "Not indicated"
        },
        "contextual_factors": {
            "sleep_quality": responses.get('sleep_last_night', ''),
            "fatigue_level": responses.get('fatigue_noticed', ''),
            "pain_or_discomfort": responses.get('current_pain', ''),
            "anxiety_level": responses.get('anxiety_level', ''),
            "emotional_state": "Cooperative and engaged",
            "medications": responses.get('current_medications', ''),
            "substance_use": "Not addressed",
            "testing_environment": "Controlled clinical setting",
            "previous_testing": "Not addressed"
        },
        "attention_span_comparison": {
            "attention_during_commands": responses.get('command_comprehension', ''),
            "attention_during_spelling": responses.get('spelling_difficulty', ''),
            "attention_during_arithmetic": responses.get('arithmetic_confidence', ''),
            "attention_during_serial_tasks": "To be assessed by clinician",
            "relative_strengths": "To be determined by clinician",
            "relative_weaknesses": "To be determined by clinician",
            "task_difficulty_effect": "To be assessed by clinician"
        },
        "assessment_summary": {
            "attention_span_level": "To be determined by clinician",
            "sustained_attention_status": "To be determined by clinician",
            "selective_attention_status": "To be determined by clinician",
            "concentration_quality": responses.get('focus_during_test', ''),
            "attention_strengths": "To be determined by clinician",
            "attention_weaknesses": "To be determined by clinician",
            "distractibility_level": responses.get('distraction_level', ''),
            "attention_disorder_indicators": "Not indicated",
            "fatigue_impact": responses.get('fatigue_noticed', ''),
            "contributing_factors": f"Sleep: {responses.get('sleep_last_night', '')}, Pain: {responses.get('current_pain', '')}, Anxiety: {responses.get('anxiety_level', '')}",
            "recommendations": "Routine attention screening, environmental optimization",
            "specialist_referral": "Not indicated at this time"
        }
    }

    # Create assessment object
    assessment = AttentionSpanAssessment(**assessment_data)

    # Save to file if path provided
    if output_path is None:
        output_path = Path("outputs") / f"{patient_name.lower().replace(' ', '_')}_attention_span.json"

    # Create outputs directory if it doesn't exist
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save assessment as JSON
    with open(output_path, 'w') as f:
        json.dump(assessment.model_dump(), f, indent=2)

    print(f"\n✓ Assessment saved to: {output_path}")

    return assessment


def evaluate_attention_span(
    patient_name: str,
    output_path: Optional[Path] = None,
    use_schema_prompt: bool = True,
    prompt_style: PromptStyle = PromptStyle.DETAILED,
    client: Optional[MedKitClient] = None,
    patient_context: Optional[str] = None,
) -> AttentionSpanAssessment:
    """
    Evaluate patient attention span and concentration capabilities through interactive questionnaire.

    Args:
        patient_name: Name or identifier of the patient
        output_path: Optional path to save JSON output. Defaults to outputs/{patient_name}_attention_span.json
        use_schema_prompt: Whether to use PydanticPromptGenerator for schema
        prompt_style: Style of schema prompt (DETAILED, CONCISE, TECHNICAL)
        client: Optional MedKitClient for LLM question generation
        patient_context: Optional patient context for question customization

    Returns:
        AttentionSpanAssessment: Validated attention span assessment object
    """
    if not patient_name or not patient_name.strip():
        raise ValueError("Patient name cannot be empty")

    # Ask patient questions interactively
    print(f"\nStarting attention span assessment for: {patient_name}")
    responses = ask_attention_span_questions(client, patient_context, prompt_style)

    # Create assessment from responses
    assessment = create_attention_assessment_from_responses(patient_name, responses, output_path)

    return assessment


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(
        description="Evaluate patient attention span and concentration capabilities through structured assessment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default - saves to outputs/patient_attention_span.json
  python exam_attention_span.py "John Doe"

  # Custom output path
  python exam_attention_span.py "John Doe" -o custom_assessment.json

  # With concise prompting
  python exam_attention_span.py "John Doe" --concise

Attention Span Testing Protocol:
  1. COMMAND FOLLOWING: Progress from simple to complex
     - Single step: "Close your eyes"
     - Two step: "Take off your glasses and put them on the table"
     - Three step: "Take off all clothes, put on patient gown, sit on examining table"
     - Complex: Commands with conditional elements

  2. SPELLING TASKS: Forward and backward
     - Spell "WORLD" forward (W-O-R-L-D)
     - Spell "WORLD" backward (D-L-R-O-W)

  3. SERIAL TASKS: Recitation and backward counting
     - Months backward from December
     - Days backward from Sunday
     - Count backward from 20
     - Serial 7s (100, 93, 86, 79...)

  4. ARITHMETIC ATTENTION: Focus during calculation
     - Simple arithmetic without paper/pencil
     - Multiple calculations in sequence
     - Increasing difficulty level

  5. SUSTAINED ATTENTION: Monitor throughout all tasks
     - Initial focus quality
     - Maintenance of focus over time
     - Fatigue effects
     - Recovery with breaks
        """
    )
    parser.add_argument("patient", nargs='*', default=['unknown'], help="Name or identifier of the patient (default: 'unknown')")
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Path to save JSON output. Defaults to outputs/{patient_name}_attention_span.json"
    )
    parser.add_argument(
        "--concise",
        action="store_true",
        help="Use concise prompt style (faster generation)"
    )

    args = parser.parse_args()

    try:
        patient_name = " ".join(args.patient)
        prompt_style = PromptStyle.CONCISE if args.concise else PromptStyle.DETAILED

        result = evaluate_attention_span(
            patient_name=patient_name,
            output_path=args.output,
            prompt_style=prompt_style,
        )
        print("✓ Success!")

    except Exception as e:
        print(f"✗ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
